In [184]:
# attempt to check how things are

In [4]:
import glyph_utils

In [6]:
glyph_utils.gardiner_to_hieroglyphics('Aa20')

'𓐢'

In [ ]:
glyph_utils.gard

In [1]:
import openai

In [2]:
system_prompt = """Assess the hieroglyphics translation based on the following scales and include your assessment in a JSON response:

1. **quality:**  
   - **1 (Poor):** Significant grammatical or logical errors.
   - **2 (Fair):** Generally correct but may need minor corrections or clarifications.
   - **3 (Good):** Fully reasonable seeming translation.

2. **interest:**  
   - **1 (Not Interesting):** Lacks novelty or fails to engage.
   - **2 (Somewhat Interesting):** Contains interesting elements but not compelling throughout.
   - **3 (Very Interesting):** Interesting OR sounds like ancient wisdom OR could be interpreted in a sexual way.

### **Instructions for the LLM:**  
- Respond only using the JSON object format specified above, without any additional text or comments.
- Evaluate both the **quality** and **interest level** of the translation according to the scales provided.
- Ensure the JSON output is correctly formatted and free of errors.

Example of the required JSON response:
{
  "quality": <int>,
  "interest": <int>
}"""


# blessing or a curse

In [42]:
glyph = "You can sit on the border of the river. The fields I gave to you, as you said."

In [16]:
ask_llm(glyph, system_prompt=system_prompt)

'{\n  "quality": 2,\n  "interest": 2\n}'

In [7]:
from openai import OpenAI  # Make sure to import the correct library

In [206]:
import os
from dotenv import load_dotenv

load_dotenv()
api_key = os.getenv('OPENAI_API_KEY')
if not api_key:
    raise ValueError('OPENAI_API_KEY not found in environment or .env file')

def ask_llm(prompt, system_prompt="you are a helpful assistant", temp=0.8, model="gpt-40"):
    model_name = "gpt-4o"
    client = OpenAI(api_key=api_key)
    completion = client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ]
    )

    return completion.choices[0].message.content

In [15]:
ask_llm(glyph)

'{\n  "quality": 3,\n  "interest": 2\n}'

In [187]:
from matviz.helpers_graphing import *
fnames = glob.glob("out/*.csv")

fnames

['out/translated_0.9.csv',
 'out/translated_0.8.csv',
 'out/translated_1.0.csv',
 'out/merged_translations.csv',
 'out/translated_0.6.csv',
 'out/translated_0.7.csv',
 'out/translated_0.5.csv']

In [201]:
df = pd.read_csv("out/merged_translations.csv")
df
# select only one translation to review
df = df.groupby('english').head(1)

In [199]:
len(df.groupby('english').head(1))

15825

In [200]:
len(set(df['glyph'])), len(set(df['english']))

(17446, 15826)

In [155]:
all_temps = ['0.9', '0.8', '1.0', '0.7']
all_temps = ['0.5', '0.6']

In [156]:
all_translations = {k[-7:-4]: pd.read_csv(k) for k in fnames}
# all_translations

In [157]:
all_translations.keys()

dict_keys(['0.9', '0.8', '1.0', '0.6', '0.7', '0.5'])

In [158]:
ii = 0
content_list = []
temps_list = []
glyph_list = []
gardiner_list = []
for cur_temp in all_temps:
    cur = all_translations[cur_temp]
    content_list += list(cur['english'].values)
    temps_list += [cur_temp] * len(cur)
    glyph_list += list(cur['glyph'].values)
    gardiner_list += list(cur['gardiner'].values)

In [159]:
{cur_temp: len(all_translations[cur_temp]) for cur_temp in all_temps}

{'0.5': 38, '0.6': 43}

In [193]:
content_list

['Priest of the Cheop, administrator of the royal property Nefer-nisut.',
 "The priest of the Sahura, the wab priest of the king, the priest of the Cheop, the priest of the Neferirkare, the priest of the Chentit, the served by the great God. The administrator of the king's property Nefer-bau-Ptah, the priest of his lord Dedet-tawi, whom the daughter of the daughter of the daughter of the daughter of the daughter of the daughter of the daughter of the daughter of the daughter.",
 "I performed the Maat, I performed the King of Upper and Lower Egypt Kheperkare, beloved of I. To my Lord, to the great God, Kai-em-nebef, one of his Lord's lovers, one of his Lord's lovers, Kai-em-anch.",
 'He will not hear.',
 "John's bread: 1, Fauliges-tree drugs: 1, beef fat: 1, wine: 1.",
 '1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time',
 'I acted to see his crocodiles.',
 'If you look at a man with a disturbance to a man’s disturbance There is no burning in oil in the residence.',
 'The priest of the Cheop, the wab priest of the king, the predecessor of the great good and the guardian of God. The administrator of the royal property, the head of the great good, the priest of the Cheop, the head of the houses, the writer of the royal property, the guardian of the great god, the administrator of the royal property Nefer-nisut.',
 'It is a thunder in all parts of his body.',
 'Four vessels to cause his legs to do what is against him. :',
 'Then you will know the misconduct of any misconduct associated with death. Dead, dead, dead, dead, dead, dead, dead, dead, dead, dead, dead, dead, dead, dead.',
 'He may be buried in the western cemetery by being very beautiful old with the Great God, the administrator of the royal property Nefer-nisut.',
 'See, you are searching for my heart.',
 'Do not cause it to be done with jn.wt-natron in any part of the body.',
 'Four vessels were given to my feet, to my neck.',
 'There is no dead, no dead.',
 'It will be given in a ḥnt.w plant, plant slurry.',
 'See what is on his abdomen when he throw out of his feet in any part of his abdomen.',
 'I have gone, so that I have given them to you in a room that is on The foreign countries, which are on them, rush to the way.',
 'If you find a.t swallow of the disease in his abdomen by getting to the bone Crusade, Johannis Bread, Johannis Bread: 1, Honey: 1.',
 'by A.',
 'The meat, you say about him, one with a wound in his nose, one in his ears. He reaches to the bone his damage to his upper arm, a disease that he treats.',
 'I complained to me, I complained to me, because he knew his weapons and his weapons.',
 'Everyone is on the way to remove me from yound The dead, the dead, the dead, the dead, the dead.',
 'They are removed in plant bread.',
 'You will not drink, for I am Thot who ask me.',
 'See, what is done against you is more than his name. I was a crocodile in every part of my body.',
 'See, you are removed from the back.',
 'When it comes to me, I have given it to me. I am with you in the mouth of the stone.',
 'If you look at a man with a wound in his nose hole, which reaches to the bone, then you should say: His neck is swallowed, so that you do not know it, so that you are a child who has been in it every day.',
 'My companion was like a flight to me.',
 'The house manager and the worfler in your eye.',
 'Another for the removal of a swelling:',
 'The first time of the webery.',
 'The water of the Tamariske is drunk.',
 'See, you are placed behind it.',
 '1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 The',
 'Give them to me from the mouth. The words of those who go.',
 'will be linked to it.',
 'There was a complaint to make a disturbance that came from me.',
 'There was no one to whom my name was given to me.',
 'There is nothing to do with him.',
 'The oldest Chentischi of the palace, served by the great God, administrator of the royal property and priest of the Hathor, the worthy Chentischi.',
 'Hereditary noble and local prince, seal-bearer of the king, the sole friend, overseer of the treasury, Gehes.',
 'x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x',
 'The roads are to the place where you are, who do the good.',
 'So you must then clean it after the salt oil you find. Remove a.t swallow of its cooling:',
 'You, Imi-ha-em-a',
 'I acted for Chnum of eternity.',
 'He gave me the mouth of Re with plant slurry.',
 'There is no one who knows the four nodes behind my back in four times.',
 'He did not do anything.',
 "Priest of the Cheop and Priest of the Cheop, one of his Lord's lovers, Mer-ib.",
 'The servant of the great God, the priest of the Cheop and the predecessor of the great good. Priest of the Nebka, Priest of the Neferirkare, Supplier of the Great God, Administrator of the Royal Property Init.',
 'My children were in this my body. Those who are in the water of the water of the death,',
 "If you look at a man whose findings are well preserved, then you should say: In any part of a man's body, you find it by his mouth.",
 'It was like Re, and it was like Re, and it was like Re.',
 'It will be caused to be caused to be caused to be caused to be caused.',
 'But if he finds me in the residence, And make sure that you know every thing.',
 'It is the heart to drink by the ears.',
 'See, there is no warrior on my day.',
 'Giving the Scriptures of every office of the one who performs the Maat.',
 'The Supervisor of the Priests of the Nefer, Priests of the Nefer, Managers of the Royal Property, Chentischi of the Palace, Chairman of every work of the King Senedjem-ib. The Chairman of the Acts of the King, Acts of the King, Acts of the King, Acts of the King, Acts of the King, Acts of the King, Acts of the King, Acts of the King, Acts of the King',
 'Johannis Bread: 1, Sodium: 1, Ocker: 1, Sub-Egyptian salt: 1. Grass: 1, grass: 1, f plants: 1, jbr oil: 1, plant slurry: 1, grass: 1, fruit of the tḥw plant: 1, oil : 1. The',
 'The eye is in my hand, I know. Let me tell you, let me tell you, let me tell you.',
 'I gave it to yound',
 'You act for me like you, the dead, the dead, the dead, the dead. The knowledge of the knowledge of the knowledge of the knowledge of the knowledge of the knowledge of the knowledge of the knowledge. There is no translation',
 'If it is',
 'The Chief of the Chief of the Chief of the Chief of the Chief of the Chief of the Chief of the Chief of the Chief The house manager of the servant of the great God, the servant of his Lord Set-kai.',
 'There is no one who knows your name by walking on his upper arm.',
 '1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1',
 'He may be buried in the West by being very beautiful old with the great God, the supervisor of the priests of the palace, the administrator of the royal property. The administrator of the palace, guard of the secret, administrator of the royal property, head of the writers of the royal property in front of the Wab priest of the king, served by the great God, administrator of the royal property, guard of the secret of The Writer of the Acts, Chairman of the Acts Writers of the King, Supplier of the Great God at the Great God, Kai-em-anch.',
 'You act for me the night of my night, like the night of my night.',
 'Those who were on the day of worship, those who were on the day of worship.',
 'Johannis Bread: 1, wheat smoke: 1, grain: 1, bottle Reduced plants: 1, plant slurry: 1, oil : 1.',
 '(According to the Qur’an, the Qur’an is the Qur’an, and the Qur’an is the Qur’an, and the Qur’an is the Qur’an.',
 'I was in the residence of the one who was in his pyramid.',
 'What to do:',
 'Don’t get closer to the stomach to remove from the outside.',
 ':']

In [203]:
content_list = list(df['english'].values)

In [204]:
content_list

['Priest of the Cheop, administrator of the royal property and administrator of the royal property.',
 'It will be taken over 4 days.',
 'O predecessor of all predecessors in eternity,',
 'The righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous You, the king, are in his body, and you say:',
 'It is useful for the servants of his abdomen according to his possessions.',
 'Blood from his nose.',
 "His mother, the administrator of the king's property, the guardian of the great God, the administrator of the king's property and the predecessor of the great good Nefer-nisut.",
 "John's bread: 1, sweet beer: 1.",
 'Is it in the presence of the hereditary noble and local prince, seal-bearer of the king? The only friend, overseer of troops, he says, Mehi, his name is Nen-Seschem-Zepter.',
 'Hereditary noble and local prince, seal-bearer of the king, the sole friend, overseer of the treasury of his neck, beloved one.',
 'On the other hand, on the other hand, on the other hand, on the other hand, on the other hand, on the other hand, on the other hand, on the other hand, on the other hand, on the other hand, on the other hand. 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1 to 1',
 'The administrator of the royal property, the wab priest of the king, the guardian of the great god, the sister of the West.',
 'I acted for myself as a result of my succession.',
 'Remedies for the fixed smell: Every bad thing of what is done against it against any body:',
 'His heart to punish him against what he does.',
 'Go out of your eye.',
 'The worshiper, he made the righteous.',
 'After that, my heart was weak.',
 'by J.',
 'It was what I praised before the high officials.',
 'The sight of any evil.',
 'Do not be in your behavior.',
 'Another for the drink of the one who goes:',
 'I have done that according to what I have done.',
 'The place of the king, let him be guilty.',
 'My vessels are my vessels, my vessels are my vessels.',
 'The ḥnḥn.t swallow of the ry.t swallow on his upper leg, on his upper leg, on his walk.',
 'Your daughter, overseer of foreign mercenaries, overseer of foreign mercenaries.',
 'I will not be in your body to go to the lake.',
 'You will not find a blood test in his nose. His subcutaneous region is in his neck, a disease that I will treat.',
 'I have spent the time for you, and I have spent the time for yound',
 'See what is on his abdomen when he throws his upper arm with him.',
 'And they let me make a place where I was born.',
 "The priest of the Hathor, one of his Lord's lovers, guard of the secret of the Wab priest of the King, one of his Lord's lovers, Ra-wer.",
 'I will see his outcome before me, because of what has been done against him.',
 'There is no translation',
 'The servant of the great God, the administrator of the royal property, the administrator of all his places, the administrator of his lord every day, Ni-maat-Re, justified.',
 ':',
 '1 Libation, 1 smoke fire, 1 smoke fire, 1 fixed smoke oil, 1 fixed smoke oil, 1 cup of water, 1 cup of wheat smoke. 2 portions, 1 portion, 1 portion, 1 portion, 1 portion, 1 portion, 1 portion, 1 portion, 1 portion, 1 portion, 1 portion, 1 portion, 1 portion, 1 portion, 1 portion, 1 por 1 of 1 of 1',
 'On the face of Atum, he placed his hand.',
 'mdb.w-plants : 1, nms.w-plants, which contain: 1. qw.t-plants: 1, wine: 1, Stark Beer: 1.',
 'See what I have done.',
 'Your flesh says about it:',
 'A.t swallow of the Dornakazie.',
 'The',
 'He gave blood to his chest, so that he was healed and his damage was broken.',
 'His nose was shrinking in the mouth of that',
 'I was one beloved of his lord, Chnumhotep, born of Mam.',
 'The wrecked in the abdomen He brings to you and to the one to the other.',
 'If you investigate a man with a wound in his nose hole in his ears, which reaches to the bone a bone that broke his damage to his damage to his damage to his damage to his damage to his damage to his damage to his damage to his damage to his damage :',
 'Re said to him, It is in the shadow of the shadow.',
 'The praise is in it.',
 'He is the great one, and he is the great one, and he is the great one.',
 'A good thing to do in every work of the king, the predecessor of the house of his fighting in it, a guardian to the king of the king of the king of the king of the king of the king of the king of the king.',
 'to protect the Min from the nobles in it.',
 'If you find a.t swallow of fat, then you should say: It is the case that there is no blame in any part of the body.',
 'The lady of the house, associated with any evil thing, associated with any evil.',
 'then you say about him, A man with a wound',
 'He may be buried in the western cemetery by being very beautiful old, the Lady of God. The only friend, the leader of the sub-Egypt Iri-pat, the predecessor of the festival of the festival of the festival of the festival of the festival of the festival of the festival of the festival of the festival of the festival of the festival of the festival of the festival The',
 'I acted like the smell in my eye, like every thing of my heart, like the smell of a man in my eye. If you say, his flesh, a wound in his nose is broken, a wound in his neck is broken, a wound in his neck is broken, a wound in his neck is broken.',
 'Hereditary noble and local prince, seal-bearer of the king, the sole friend, overseer of the treasury, Gehes.',
 'Then you must then put your hand.',
 'He may be buried in the western cemetery by being very beautiful old. The servant of the great God, the administrator of the royal property and the servant of the great God Kai-pi.',
 'He served at Anubis, the supervisor of the treasury manager Kai-em-amch.',
 'He is the one who lacks his weapons.',
 'In the words of the Holy Prophet, the Holy Prophet, the Holy Prophet, the Holy Prophet.',
 'The son of the wab priest of the king, the predecessor of his great good, the predecessor of the Chentuschi Imi.',
 'Bread and beer: 1.',
 'They will be in water.',
 'After that, his two legs are well preserved in the eye. The meat of the one who gave birth to me, oh Samanu.',
 'Your bar is at the top of your head.',
 'If you appear in the after, it will be removed from it.',
 'Do the same as what the servant did for me, a man in your mouth.',
 'The strike to',
 'The name of it',
 'Their rooms have been fixed to come to his possession.',
 'a man belongs to what is not to punish his mouth.',
 'I also said to him, It is a pleasant pleasant. Another 〈zum〉 causes it to be healthier by giving its remedy:',
 'If you look at a man from the district of the foreign countries to the district of what is in this district, then you should say:',
 'It will be given to the wound, so that you have completed the bad things.',
 'His beloved son Sheditef.',
 'As for this landman, he asks his enemies to be on his arms to do that. I belong to my children, to my children, to my children, to my children, to my children, to my children, to my children, to my children. The',
 'then you say:',
 'The sealers were in the mouths of all the gods in the course of every day of the great god. The truth, the truth, the truth, the truth, the truth, the truth, the truth, the truth, the truth.',
 'The courtyard, the chief of the palace, the administrator of the royal property, one belonging to his Lord, the Chentischi of the palace, the predecessor of his place, Kai-nefer.',
 'Horus, the caregiver, says: There is no one who knows his name among men. Refrigeration of the gods of the hills of the dead, the dead, the dead, etc.',
 'It is a bad thing that I will do.',
 'Good is good.',
 'If you find any sft of a man or woman suffering from her suffering, His meat, his fingers, two times the opening of the opening of his wound has swallowed to his jb-heart when he flies to the opening of his jb-heart. He will not sit next to any bad thing.',
 'The worshippers, behold, you are here.',
 'The Chief of the Chief of the Chief of the Chief of the Chief of the Chief of the Chief of the Chief The chief of the house, the guardian of the great God, the guardian of his Lord Seschem-nefer.',
 'See, there is no beef.',
 'A sacrifice to the king and Osiris, the lord of Busiris, Chontamenti, the lord of Abydos. May he open the roads to the west, to every foreign country.',
 'His oldest son, the guardian of the food of his children. He hurt, he hurt, he hurt.',
 'He may be buried in the West by being very beautiful old.',
 'The friends of what is, there are no fathers on it.',
 'In the words of the Holy Prophet, the Holy Prophet, the Holy Prophet, the Holy Prophet, the Holy Prophet, the Holy Prophet.',
 'O, yet no one has spoken to him in a matter, in a matter, in a matter, in a matter, in a matter, in a matter, in a matter. 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1',
 'Whoever spends the day, I will teach you. I am in the place of the suffering that is in every part of my body.',
 'He gave me the water to come. The sight of walking in the eyes comes.',
 'to be destroyed.',
 'The dead, the dead, the dead, the dead, the dead, the dead. The end of the end of the end of the end of the end.',
 'When it comes to it, it will be swallowed.',
 'The priest, the wab priest of the king, the chairman of the house, the servant of the great god, the Lord of the West, the chairman of the great god, the chairman of the great god, the chairman of the great god, the chair The administrator of the kingdom, the head of the Phyles, a daily servant with Asosi, a guardian with his Lord every day, justified, the administrator of the royal property, the administrator of the royal property, the administrator of the royal property The administrator of the royal property, the administrator of the royal property, the administrator of the royal property, the administrator of the royal property, the administrator of the royal property, the administrator of the royal property, the administrator of the royal property',
 'What he gave to another:',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1',
 'O Lord, O Lord, O Lord, O Lord, O Lord, O Lord, O Lord, O Lord! Everything in my face, my arms.',
 'I don’t know how to get closer to me.',
 'I ordered to you to go to him.',
 'I acted according to your knowledge, according to my command.',
 'There is no one for you on the opening of that wound.',
 'His Majesty said:',
 'See, you are more depressed than it is.',
 'He is the man, and he is the man.',
 'to him my father in need, a caregiver with the great God, a caregiver with the great God, Imi. The writer, the predecessor of the cities, the predecessor of the cities, the administrator of the country, the administrator of the great good, the administrator of the great good, the administrator of the royal property Kai.',
 'Moreover, it is done in an exhausted way as something that has not been seen. O associated associated associated associated associated associated',
 'He will command me to come.',
 'As for that I was in any part of the body of a man, I was in an accusation. It is the Ka of all things that I give to my heart, which I give to the mountains of the things of the north, which I give to my children.',
 "What is done by the overseer of the health of a man, you find it without putting it in a room: In any part of a man's body, you find him burned.",
 'The administrator of the royal property, the elderly in the house of the mistress, with him, the righteous, after I had performed his plans like him. His character belongs to him, his strength belongs to the brightness of the brightness of the brightness.',
 "May the Min, the Great God, the Lord of Abydos, give me an invocation offering of bread and beer, bulls and birds for him a year of death. New Year's Day, Thot-Fest, Year's Beginning, Wag-Fest, every holiday, every day.",
 'He does not know him.',
 'It is a good thing.',
 'The Lord of Jty.',
 'It is done to yound',
 'Don’t get closer to your room.',
 'The predecessor of the writers of the king, the predecessor of the great good and the guardian of the great God Kai-huti.',
 'See, misconduct is in his name.',
 'When one goes to me, he is in his name. You may be good in the name of any body.',
 'It will not be given to him, so that he may see the eye.',
 'He did the same for himself, and he did all his things. Thou shalt speak to the heavens, thou shalt speak to your heavens.',
 'There is nothing that you do not know, there is nothing that you do not know.',
 'Remove the disease trigger in it:',
 'Four vessels do not receive those who are against you, so that they may be in their hearts. The mouth of the mouth of the mouth of the mouth of the mouth of the mouth of the mouth.',
 'The righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous On the Day of Resurrection, on the Day of Resurrection, on the Day of Resurrection, on the Day of Resurrection, on the Day of Resurrection, on the Day of Resurrection, on the Day of Resurrection, on the Day of Resurre 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time',
 'The generation becomes good.',
 'It is the one in front of you, who knows me in the way. I was in the shadow of the shadow of the shadow of the shadow of the shadow of the shadow of the shadow of the shadow of the shadow of the shadow. 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time',
 'Her oldest son, the manager of the royal property Nefer.',
 'O, yet a man is associated with his sword in his head, his explanations.',
 'It is his oldest son, the Chentischi of the palace, the servant of the great God, the predecessor of the Chentuschi. The Wab priest of the king in the desert, by being very beautiful old with the Great God, the Chamber Servant of the King, the Acts Writer of the King, the Chairman of the Dresch House, he may be placed in the necropolis, the by J.',
 'He served her husband Hetepund',
 'I will not open you to the one who is in your face.',
 'Do it!',
 'I belong to the man.',
 'It is the great.',
 'The administrator of the royal property, served by the great god, the wab priest of the king, the supervisor of the Chentuschi of the palace, Imi. The Chairman of the Commandments, Chairman of the Elderly, Lord of Honor to the Great God, Lord of the West, Chenemti.',
 'Let him be clarified, Chnum, whom I made in the West, when Osiris was in the shadow. His beloved in the presence of the great god in the life of the stars of the city, to which he was placed in the entire land, in this temple of the Horus, to see the perfection of the good and the perfection of the Imi-nefer, to',
 'He will not be afraid of any favour of the king, the predecessor of the righteous. He was a great one under the Majesty of the King of Upper and Lower Egypt Kheperkare, beloved of the life of eternity.',
 'to whom the appearances of the priests of the Maat were given in peace,',
 'Do not fill good.',
 'It was his oldest son, the predecessor of the Maat, the great of his Lord Antef, who said:',
 'There is no right thing.',
 'As for any popularity, my father',
 'The Supervisor of the Dead Priest Senedjem-ib Palace.',
 'A sacrifice to the king and Anubis, who is on his mountain, Imiut, the Lord of the Necropolis, the great God, the Lord of Abydos.',
 'Year 13 under the Majesty of the King of Upper and Lower Egypt Kheperkare, justified, he says:',
 'See, you are a constipation of the vessels, it will not be given to him. His good shapes, the shapes, the shapes, the shapes, the shapes, the shapes, the shapes, the shapes.',
 'He keeps his house.',
 'See, there is no one who has swallowed his name.',
 'The room of his renewal.',
 'You will not be complained about what reaches to yound',
 'This',
 'This door to the door to the door, which is in Abydos.',
 'to be removed in the beer of wine;',
 'His daughter Henut-N.',
 'Fatty: 1, Sub-Egyptian salt: 1, Propolis : 1.',
 'They do not belong to His Majesty.',
 'Another remedies:',
 'It will be done by my mistress, justified.',
 'The only friend of the king.',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1',
 'then you say about him, one with a wound: The leaves of his upper arm are at his residence.',
 'I will be greeted to your people.',
 'Another for the cooling of the body in the body:',
 'And make you go down.',
 'I also worked for the Majesty of my Lord, Intef.',
 'Blood from my neck.',
 'The neck of what has been spoken to this.',
 'Indeed, the Supreme Supreme Supreme Supreme Supreme Supreme Supreme Supreme Supreme Supreme Supreme Supreme Supreme Supreme Supply The victims of the evil, like the inhabitants of his father.',
 'He gave me and I praised me in the same way. My servant, I’m tired like my possessions.',
 'then you say about him, one with a wound in this disease:',
 'I acted according to my plans, my plans, my plans, so that I could live, by saying:',
 'When you come, they will be removed.',
 'Be salty with sweet beer: 1.',
 'He did not hurt the country in which he was born.',
 'As for the remedies to cause it to hurt: You belong to the residence, to the residence, to the residence, to the residence, to the residence.',
 'The predecessor, justified.',
 'An offering which the king gives Osiris, Lord of Busiris, Khentamenti, Lord of Abydos: an invocation offering of bread, beer, cattle, birds, alabaster, linen and clothes. every good and every good and every good and every good and every good and every good and every good and every good and every good and every good.',
 'He suffers from this speech to the height of my head.',
 'He is the name of his name, the name of his name, the name of his name.',
 'See, there is no one who knows it on it.',
 'You will be drunk from the room.',
 'Do not trust your heart.',
 'His son Kai.',
 'The Wab priest of the king, the leader of his tribe, Ra-wer.',
 'It will not happen on its two arms, like that. Drinking to the bone: 3 feet from it.',
 'In the words of the Holy Prophet, the Holy Prophet, the Holy Prophet, the Holy Prophet, the Holy Prophet.',
 'Another for the destruction of the back:',
 '1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time',
 'Then you have to prepare for him a meal from wš.tj-mineral that they have spoken against you, death.',
 'Hereditary noble and local prince, seal-bearer of the king, the sole friend, overseer of priests of the king, the wab priest of the king, Chnum.',
 'then his Majesty L.H.G. said to him,',
 'I gave one of them, one of them, one of them, one of them, one of them. The roads and the roads have been stolen.',
 'My body was before me.',
 'See, you are in your heart.',
 'It will not be caused to go out of the water.',
 'Another for the removal in the eyes:',

In [207]:
import json

# Prepare the .jsonl file with each prompt as a request
with open("batch_input.jsonl", "w") as f:
    for i, content in enumerate(content_list):
        request = {
            "custom_id": f"request-{i+1}",
            "method": "POST",
            "url": "/v1/chat/completions",
            "body": {
                "model": "gpt-4o",
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": content}
                ],
                "max_tokens": 1000
            }
        }
        f.write(json.dumps(request) + "\n")

In [208]:
len(content_list)

15825

In [209]:
from openai import OpenAI

# Initialize the OpenAI client with your API key
client = OpenAI(api_key=api_key)

# Upload the input file to the Batch API
batch_input_file = client.files.create(
    file=open("batch_input.jsonl", "rb"),
    purpose="batch"
)

In [162]:
batch_input_file

FileObject(id='file-XHAtCPvqSpxXgURBCsj7JFge', bytes=110924, created_at=1729798506, filename='batch_input.jsonl', object='file', purpose='batch', status='processed', status_details=None)

In [210]:
batch_input_file

FileObject(id='file-s8AY1tFQ19HA2AyLtcWHw1ig', bytes=21172703, created_at=1729897159, filename='batch_input.jsonl', object='file', purpose='batch', status='processed', status_details=None)

In [211]:
batch_input_file_id = batch_input_file.id

client.batches.create(
    input_file_id=batch_input_file_id,
    endpoint="/v1/chat/completions",
    completion_window="24h",
    metadata={
      "description": "big tester one"
    }
)

Batch(id='batch_671c22e67ce0819087b0722b5a2e82a0', completion_window='24h', created_at=1729897190, endpoint='/v1/chat/completions', input_file_id='file-s8AY1tFQ19HA2AyLtcWHw1ig', object='batch', status='validating', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=None, expired_at=None, expires_at=1729983590, failed_at=None, finalizing_at=None, in_progress_at=None, metadata={'description': 'big tester one'}, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0))

In [213]:
from openai import OpenAI
# client = OpenAI()

# tmp = client.batches.retrieve("batch_671594b3cf148190a5fe0c0e8e804866")
# tmp = client.batches.retrieve("batch_671aa17c67e88190934d50fb3531604d")
tmp = client.batches.retrieve("batch_671c22e67ce0819087b0722b5a2e82a0")
tmp

Batch(id='batch_671c22e67ce0819087b0722b5a2e82a0', completion_window='24h', created_at=1729897190, endpoint='/v1/chat/completions', input_file_id='file-s8AY1tFQ19HA2AyLtcWHw1ig', object='batch', status='completed', cancelled_at=None, cancelling_at=None, completed_at=1729903166, error_file_id=None, errors=None, expired_at=None, expires_at=1729983590, failed_at=None, finalizing_at=1729900819, in_progress_at=1729897196, metadata={'description': 'big tester one'}, output_file_id='file-XFOFAVergcWYJqqPEuo2IVD4', request_counts=BatchRequestCounts(completed=15825, failed=0, total=15825))

In [173]:
tmp.output_file_id

'file-3WvAe9qNzscyrWZYdUvUgHVQ'

In [215]:
from openai import OpenAI
# client = OpenAI()
client = OpenAI(api_key=api_key)
file_response2 = client.files.content(tmp.output_file_id)
print(file_response.text)

{"id": "batch_req_671598dae2188190a6e2f83d83a784a2", "custom_id": "request-1", "response": {"status_code": 200, "request_id": "8cd07714465761b53d15ea211b46e20a", "body": {"id": "chatcmpl-AKa2kesew2ewnNtwSaV5ratdutMnS", "object": "chat.completion", "created": 1729468474, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "```json\n{\n  \"quality\": 1,\n  \"interest\": 1\n}\n```", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 276, "completion_tokens": 20, "total_tokens": 296, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598db118881908652a1061c9b6e3f", "custom_id": "request-2", "response": {"status_code": 200, "request_id": "f2927c2758e5e3c92c3f0cddbd35967b", "body": {"id": "chatcmpl-AKa1xU0W7UzVUnQ6kqqXIRVwE7qUh", "object": "chat.completion", "created": 1729468425, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 3,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 240, "completion_tokens": 16, "total_tokens": 256, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598db32188190aee51a9a48de526c", "custom_id": "request-3", "response": {"status_code": 200, "request_id": "4457abdef6c9a931cb7f1625ffe3b5bc", "body": {"id": "chatcmpl-AKa2ZwhnFsUJ9ZWSdDlae3ixldlFC", "object": "chat.completion", "created": 1729468463, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 2,\n  \"interest\": 3\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 255, "completion_tokens": 16, "total_tokens": 271, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598db51588190a4436d8801c5629b", "custom_id": "request-4", "response": {"status_code": 200, "request_id": "1044fb8ae86eafb8563bfbcfafedb899", "body": {"id": "chatcmpl-AKZxoRtUaFZAfLwoHPGYKCnvsPDhh", "object": "chat.completion", "created": 1729468168, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 2,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 247, "completion_tokens": 16, "total_tokens": 263, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598db70ac8190b55c5fb58b6b89e9", "custom_id": "request-5", "response": {"status_code": 200, "request_id": "86158824649b82f6a12757fd17ef1f92", "body": {"id": "chatcmpl-AKZyMbH03jTu2f1x7LFTtre1VZPPe", "object": "chat.completion", "created": 1729468202, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "```json\n{\n  \"quality\": 1,\n  \"interest\": 1\n}\n```", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 237, "completion_tokens": 20, "total_tokens": 257, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598db8c6481908224ebfb20dbbdf8", "custom_id": "request-6", "response": {"status_code": 200, "request_id": "318c6e011dd387f890291b0e252eaf21", "body": {"id": "chatcmpl-AKZykJrJZnH2YenM1bGM7nxQLfLJr", "object": "chat.completion", "created": 1729468226, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "```json\n{\n  \"quality\": 1,\n  \"interest\": 2\n}\n```", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 254, "completion_tokens": 20, "total_tokens": 274, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dba8b88190bd4997e87a207ee5", "custom_id": "request-7", "response": {"status_code": 200, "request_id": "dc3a236716dec77ba4049c2b7ed8246b", "body": {"id": "chatcmpl-AKZz1ROoaT6xr2xFpdtWQnup3mzA6", "object": "chat.completion", "created": 1729468243, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 3,\n  \"interest\": 3\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 264, "completion_tokens": 16, "total_tokens": 280, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dbc6d881909e2d529404d6cb12", "custom_id": "request-8", "response": {"status_code": 200, "request_id": "79789da728223450ecbf8605197dc491", "body": {"id": "chatcmpl-AKZzS8cuORFY1ifbd7cyfwY7ezsKw", "object": "chat.completion", "created": 1729468270, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 2,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 278, "completion_tokens": 16, "total_tokens": 294, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dbe3c48190bd4eed9357c575ca", "custom_id": "request-9", "response": {"status_code": 200, "request_id": "494a8498eec9b0e16542efcfbf6ebce3", "body": {"id": "chatcmpl-AKZxCWX2rFrRSarcKqujGZICY3TuW", "object": "chat.completion", "created": 1729468130, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 1,\n  \"interest\": 1\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 236, "completion_tokens": 16, "total_tokens": 252, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dc11ec81909ea0108aef604f79", "custom_id": "request-10", "response": {"status_code": 200, "request_id": "7390e475d964cc728a0c9bdb91341481", "body": {"id": "chatcmpl-AKZxRw3D8lry6VXwQ9WhW6gmIsYbf", "object": "chat.completion", "created": 1729468145, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 2,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 275, "completion_tokens": 16, "total_tokens": 291, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dc2eac8190aa6b86648018a747", "custom_id": "request-11", "response": {"status_code": 200, "request_id": "2cc856a5ac2081577abc44bda8ef88f3", "body": {"id": "chatcmpl-AKZxd92F8LaCbkkaGNglKiwZv9rdG", "object": "chat.completion", "created": 1729468157, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 3,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 244, "completion_tokens": 16, "total_tokens": 260, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dc4c6c8190b222c911a7f54dd8", "custom_id": "request-12", "response": {"status_code": 200, "request_id": "1f2a867bdedff795e2c3c1b9790a7e36", "body": {"id": "chatcmpl-AKZxi3f9zraY6iQ3lelw1ZyRLWXEZ", "object": "chat.completion", "created": 1729468162, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 3,\n  \"interest\": 3\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 266, "completion_tokens": 16, "total_tokens": 282, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dc6ad48190b4a6826269a53a24", "custom_id": "request-13", "response": {"status_code": 200, "request_id": "8892d274213afe34414332e14967c218", "body": {"id": "chatcmpl-AKZxq13PJt0iHfFbtctTpHjcJqXlG", "object": "chat.completion", "created": 1729468170, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "```json\n{\n  \"quality\": 2,\n  \"interest\": 2\n}\n```", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 239, "completion_tokens": 20, "total_tokens": 259, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dc886c81909dd2cce0cc382042", "custom_id": "request-14", "response": {"status_code": 200, "request_id": "b3c72ee1121612385528710b11de5d24", "body": {"id": "chatcmpl-AKZyM10qAe4OUvBn3shzYF7dcRESV", "object": "chat.completion", "created": 1729468202, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 3,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 243, "completion_tokens": 16, "total_tokens": 259, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dca60c8190a2f36be17325dfe2", "custom_id": "request-15", "response": {"status_code": 200, "request_id": "9d0b42cb8e24ab50e39caf112cacd13f", "body": {"id": "chatcmpl-AKZwvskSNqCEGfX6HTLTeCQVt51R7", "object": "chat.completion", "created": 1729468113, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 2,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 248, "completion_tokens": 16, "total_tokens": 264, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dcc3c08190a5d134b38306e62e", "custom_id": "request-16", "response": {"status_code": 200, "request_id": "aaddd34d752f59c4c545126bc37acb0d", "body": {"id": "chatcmpl-AKZz4OnZXznDHSFOa6KcsmACOXLzH", "object": "chat.completion", "created": 1729468246, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 2,\n  \"interest\": 1\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 239, "completion_tokens": 16, "total_tokens": 255, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dce1688190be175804d5d0569d", "custom_id": "request-17", "response": {"status_code": 200, "request_id": "94b117914ed488be70c7661084cdfdae", "body": {"id": "chatcmpl-AKZze9bfV1UJJ7GsBQTuWOiPsc13x", "object": "chat.completion", "created": 1729468282, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 2,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 241, "completion_tokens": 16, "total_tokens": 257, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dd0efc8190a32c75ad15a9bd6c", "custom_id": "request-18", "response": {"status_code": 200, "request_id": "4ef83f12c45330a37ea70b839206a92b", "body": {"id": "chatcmpl-AKa08yQZFPVvaxSy70kctH41RaKLs", "object": "chat.completion", "created": 1729468312, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "```json\n{\n  \"quality\": 3,\n  \"interest\": 1\n}\n```", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 240, "completion_tokens": 20, "total_tokens": 260, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dd2d8481908d3622780988c418", "custom_id": "request-19", "response": {"status_code": 200, "request_id": "bd5a7d1e117d45628be5f01a8a8fe858", "body": {"id": "chatcmpl-AKa0FNWXgOwotZ0bzxbYhB5sLcc7e", "object": "chat.completion", "created": 1729468319, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 3,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 239, "completion_tokens": 16, "total_tokens": 255, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dd4ab08190a33f48e124e2a4f3", "custom_id": "request-20", "response": {"status_code": 200, "request_id": "82052bec8f6b4a2893b9a4c5005c5fb8", "body": {"id": "chatcmpl-AKZzWKKEp1ZfJ0J2fxmY8ef3FlfEl", "object": "chat.completion", "created": 1729468274, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 2,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 264, "completion_tokens": 16, "total_tokens": 280, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dd67c8819084d23b0e35afab24", "custom_id": "request-21", "response": {"status_code": 200, "request_id": "894153030443a509ed8a5447863a7697", "body": {"id": "chatcmpl-AKa04tRaOXGlriotCtZHEmXcnSYKz", "object": "chat.completion", "created": 1729468308, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "```json\n{\n  \"quality\": 2,\n  \"interest\": 2\n}\n```", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 265, "completion_tokens": 20, "total_tokens": 285, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dd85148190b346fce2e7249ae5", "custom_id": "request-22", "response": {"status_code": 200, "request_id": "e6c0225f717c3d15f81e999bac7d986b", "body": {"id": "chatcmpl-AKa0gDNxFLCGvESaq5SOicd1pEQWB", "object": "chat.completion", "created": 1729468346, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "```json\n{\n  \"quality\": 1,\n  \"interest\": 1\n}\n```", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 259, "completion_tokens": 20, "total_tokens": 279, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598dda3ec8190aa825ee073ddab3e", "custom_id": "request-23", "response": {"status_code": 200, "request_id": "d9d3b9a28fcacb443ce8fbd51884afdf", "body": {"id": "chatcmpl-AKa1ndmaMsEwOCpYzKN5aoBEytlhm", "object": "chat.completion", "created": 1729468415, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "```json\n{\n  \"quality\": 1,\n  \"interest\": 2\n}\n```", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 424, "completion_tokens": 20, "total_tokens": 444, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598ddc1a4819081e536381901a2be", "custom_id": "request-24", "response": {"status_code": 200, "request_id": "6479f879f11e428cbe9fc5a13808d7d6", "body": {"id": "chatcmpl-AKZvLIqUdipmTUGhluXLIkwCpiDWN", "object": "chat.completion", "created": 1729468015, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 1,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 246, "completion_tokens": 16, "total_tokens": 262, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598ddddb88190a72a1d56928685ed", "custom_id": "request-25", "response": {"status_code": 200, "request_id": "d1e04cf4163ccac9e6ee62842fe7022d", "body": {"id": "chatcmpl-AKZwCW8cWJt2re9YCMyC2LCjHxQmJ", "object": "chat.completion", "created": 1729468068, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 1,\n  \"interest\": 1\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 248, "completion_tokens": 16, "total_tokens": 264, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598de0b688190b0a60e676a1b359d", "custom_id": "request-26", "response": {"status_code": 200, "request_id": "0144bba09bc961087d3c60ffe6b5dae6", "body": {"id": "chatcmpl-AKZx8S6McltVMM1bb7ZWEsgJ4aFJJ", "object": "chat.completion", "created": 1729468126, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 1,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 247, "completion_tokens": 16, "total_tokens": 263, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}
{"id": "batch_req_671598de29cc81909688e568459a53ed", "custom_id": "request-27", "response": {"status_code": 200, "request_id": "b6ef6aabb2a8f56ab512645cb68dfefc", "body": {"id": "chatcmpl-AKZy5rWbIaRjqnRB7swPWSX8nR3wj", "object": "chat.completion", "created": 1729468185, "model": "gpt-4o-2024-08-06", "choices": [{"index": 0, "message": {"role": "assistant", "content": "{\n  \"quality\": 2,\n  \"interest\": 2\n}", "refusal": null}, "logprobs": null, "finish_reason": "stop"}], "usage": {"prompt_tokens": 240, "completion_tokens": 16, "total_tokens": 256, "prompt_tokens_details": {"cached_tokens": 0}, "completion_tokens_details": {"reasoning_tokens": 0}}, "system_fingerprint": "fp_a7d06e42a7"}}, "error": null}

In [175]:
for w in file_response.text.split("\n")[-1]:
    print("trying")
    json.loads(w)

In [24]:
import json

,Unnamed: 0,gardiner,glyph,english
0,0,Aa1 G43 I9 G43 R8 U36 M23 X1 D21 Aa1 M23 X1 N3...,𓐍 𓅱 𓆑 𓅱 𓊹 𓍛 𓇓 𓏏 𓂋 𓐍 𓇓 𓏏 𓈖 𓊪 𓇋,"Priest of the Cheop, administrator of the roya..."
1,1,D46 D21 A24 D21 N5 4,𓂧 𓂋 𓀜 𓂋 𓇳 4,It will be taken over 4 days.
2,2,G17 D21 / / / / V31A Y1 G17 / N35 G21 V28 N5 V...,𓅓 𓂋 / / / / 𓎡A 𓏛 𓅓 / 𓈖 𓅘 𓎛 𓇳 𓎛 𓎛,"O predecessor of all predecessors in eternity,"
3,3,/ / / / / / / / / / U7 D21 X1 I9 G17 O34 N35 I...,/ / / / / / / / / / 𓌻 𓂋 𓏏 𓆑 𓅓 𓊃 𓈖 𓆑 / 𓄤 𓏏 [E14...,The righteous righteous righteous righteous ri...
4,4,G25 Aa1 Y1 N35 U31 X1 O1 A1 Z2 N35 X1 D21 F32 ...,𓅜 𓐍 𓏛 𓈖 𓍕 𓏏 𓉐 𓀀 𓏥 𓈖 𓏏 𓂋 𓄡 𓏏 𓏤 𓆑 𓂋 𓐍 𓏏 𓏛 𓏥,It is useful for the servants of his abdomen a...
...,...,...,...,...
17800,31,M17 Z7 G17 D36 V31A Z4 Y1 A1 W19 M17 O4 G1 D58...,𓇋 𓏲 𓅓 𓂝 𓎡A 𓏭 𓏛 𓀀 𓏇 𓇋 𓉔 𓄿 𓃀 𓂻 𓈖 𓀀 𓄖 𓅓 𓀀,My companion was like a flight to me.
17801,32,/ / O1 Z1 G17 D21 D34 G1 A24 A1 Z2 D21 D4 X1 Z...,/ / 𓉐 𓏤 𓅓 𓂋 𓂚 𓄿 𓀜 𓀀 𓏥 𓂋 𓁹 𓏏 𓏤 𓎡A,The house manager and the worfler in your eye.
17803,34,O34 Q3 O50 D1 Q3 Z4 N35 D21 M17 M17 X1 O1,𓊃 𓊪 𓊗 𓁶 𓊪 𓏭 𓈖 𓂋 𓇋 𓇋 𓏏 𓉐,The first time of the webery.
17804,35,S29 G36 D21 M17 N35A A2 Z7 S29 X1 N35 W24 Z7 T...,𓋴 𓅨 𓂋 𓇋 𓈖A 𓀁 𓏲 𓋴 𓏏 𓈖 𓏌 𓏲 𓌙 𓅯 𓏛 𓏥 𓈖 𓇋 𓏏 𓎛 𓏲 𓌙 𓏱...,The water of the Tamariske is drunk.
17805,36,G17 D36 V31A X1 Z7 G17 D21 Aa1 Y1 V31A D21 D36...,𓅓 𓂝 𓎡A 𓏏 𓏲 𓅓 𓂋 𓐍 𓏛 𓎡A 𓂋 𓂝 𓏏 𓁷 𓏤 𓐟 𓏤 𓋴 𓏏,"See, you are placed behind it."

In [176]:
df = pd.DataFrame(np.concatenate([[temps_list], [content_list], [glyph_list], [gardiner_list]]), index=["temps", "content", "glyphs", "gardiner"]).T
# pd.DataFrame(response_list)

In [177]:
df

,temps,content,glyphs,gardiner
0,0.5,"Priest of the Cheop, administrator of the roya...",𓐍 𓅱 𓆑 𓅱 𓊹 𓍛 𓇓 𓏏 𓂋 𓐍 𓇓 𓏏 𓈖 𓄤,Aa1 G43 I9 G43 R8 U36 M23 X1 D21 Aa1 M23 X1 N3...
1,0.5,"The priest of the Sahura, the wab priest of th...",𓇳 𓃃 𓅱 𓊹 𓍛 𓇓 𓏏 𓈖 𓀆 𓐍 𓅱 𓆑 𓅱 𓊹 𓍛 𓇳 𓄤 𓁹 𓂓 𓊹 𓍛 𓏃 𓏏 ...,N5 D61 G43 R8 U36 M23 X1 N35 A6 Aa1 G43 I9 G43...
2,0.5,"I performed the Maat, I performed the King of ...",𓇋 𓅱 𓁹 𓈖 𓅱 𓌳 𓐙 𓂝 𓏏 𓁦 𓁹 𓈖 𓇓 𓏏 𓆤 𓏏 𓏏 𓇳 𓆣 𓂓 𓌻 𓂋 𓇋 ...,M17 G43 D4 N35 G43 U1 Aa11 D36 X1 C10 D4 N35 M...
3,0.5,He will not hear.,𓂜 𓈖 𓄔 𓅓 𓈖 𓆑 𓏏 𓏲,D35 N35 F21 G17 N35 I9 X1 Z7
4,0.5,"John's bread: 1, Fauliges-tree drugs: 1, beef ...",𓇋 𓏲 𓈖 𓍑 𓄿 𓂋 𓏏 𓈒 𓏥 𓏤 𓆱 𓂝 𓍯 𓄿 𓈒 𓏥 𓏤 𓎙 𓂧 𓏌 𓏥 𓃒 𓏤 ...,M17 Z7 N35 U28 G1 D21 X1 N33 Z2 Z1 M3 D36 V4 G...
...,...,...,...,...
76,0.6,"(According to the Qur’an, the Qur’an is the Qu...",/ / / / / / / / / / / / / / / / / / / / / / / / /,/ / / / / / / / / / / / / / / / / / / / / / / / /
77,0.6,I was in the residence of the one who was in h...,𓈖 𓇦 𓏲 𓀀 𓅓 𓄚 𓈖 𓏌 𓏲 𓉐 𓈖 𓈖 𓏏 𓏭 𓍋 𓅓 𓂋 𓉴 𓉐 𓆑,N35 M37 Z7 A1 G17 F26 N35 W24 Z7 O1 N35 N35 X1...
78,0.6,What to do:,𓁹 𓂋 𓏏 𓏥 𓂋 𓊃,D4 D21 X1 Z2 D21 O34
79,0.6,Don’t get closer to the stomach to remove from...,𓅓 𓎡A 𓏏 𓏴 𓂻 𓏲 𓁷 𓏤 𓈖 𓏏 𓏭 𓂋 𓏤 𓄣 𓏤 𓂧 𓂋 𓀜 𓅓 𓂋 𓏲 𓏏 𓏭 𓇯,G17 V31A X1 Z9 D54 Z7 D2 Z1 N35 X1 Z4 D21 Z1 F...
80,0.6,:,/ / / / / / / / /,/ / / / / / / / /

In [133]:
len(temps_list), len(content_list), len(response_list), len(glyph_list), len(gardiner_list)

(217, 217, 217, 217, 217)

In [32]:
cur_res = response_list[0]['response']['body']['choices'][0]['message']['content']

In [225]:
df[all_txt=="I'm sorry, it seems there is a part of the content missing for me to evaluate. Could you provide the hieroglyphics translation text that needs to be assessed?"]

     Unnamed: 0 gardiner glyph english
395         395  G17 D36   𓅓 𓂝   It is

In [223]:
all_txt = np.array([cur_res['response']['body']['choices'][0]['message']['content'] for cur_res in response_list])

In [226]:
cur_res[]

{'id': 'batch_req_671c314b18988190aaef378126495d92',
 'custom_id': 'request-382',
 'response': {'status_code': 200,
  'request_id': 'baddf8b09287aa676ba0c5452c2b6921',
  'body': {'id': 'chatcmpl-AMNbCPQ6MDZ1bFJvwddzfxiIYCpmY',
   'object': 'chat.completion',
   'created': 1729897294,
   'model': 'gpt-4o-2024-08-06',
   'choices': [{'index': 0,
     'message': {'role': 'assistant',
      'content': "I'm sorry, it seems there is a part of the content missing for me to evaluate. Could you provide the hieroglyphics translation text that needs to be assessed?",
      'refusal': None},
     'logprobs': None,
     'finish_reason': 'stop'}],
   'usage': {'prompt_tokens': 235,
    'completion_tokens': 34,
    'total_tokens': 269,
    'prompt_tokens_details': {'cached_tokens': 0},
    'completion_tokens_details': {'reasoning_tokens': 0}},
   'system_fingerprint': 'fp_90354628f2'}},
 'error': None}

In [240]:
cur_txt
cur_json

{'quality': 2, 'interest': 2}

In [242]:
response_list = [json.loads(w) for w in file_response2.text.split("\n")[:-1]]
all_res = []
for cur_res in response_list:
    cur_txt = cur_res['response']['body']['choices'][0]['message']['content']
    try:
        cur_json = robust_json_loader(cur_txt)
    except:
        if cur_txt == "I'm sorry, but I cannot accurately evaluate the quality and interest of the translation without the hieroglyphics or their translated text. Could you please provide the translation for assessment?":
            cur_json = {'quality': 2, 'interest': 2}
        else:
            print(f"text is:`{cur_txt}`")
            print(df[all_txt==cur_txt]['glyph'])
            print(df[all_txt==cur_txt]['english'])
            print("")
            cur_json = {'quality': -1, 'interest': -1}
    all_res.append(cur_json)

df_all2 = pd.concat([df, pd.DataFrame(all_res)], axis=1)
df_all2

text is:`I'm sorry, it seems there is a part of the content missing for me to evaluate. Could you provide the hieroglyphics translation text that needs to be assessed?`
395    𓅓 𓂝
Name: glyph, dtype: object
395    It is
Name: english, dtype: object

text is:`I'm sorry, I can't assist with that request.`
2371    / / / / / 𓅓 𓊖 𓏏 𓏤
Name: glyph, dtype: object
2371    (According to the Qur’an, it is
Name: english, dtype: object

text is:`I'm sorry, but I need you to provide the hieroglyphics translation for assessment. Once you do, I'll be able to evaluate it based on the specified criteria.`
3419    𓇋 𓅱 𓁹 𓈖
Name: glyph, dtype: object
3419    I made
Name: english, dtype: object

text is:`I'm sorry, but I need more information about the hieroglyphics or the translation in order to provide an evaluation. Could you please provide the text or the content of the hieroglyphics in need of assessment?`
4049    𓁷 𓏤 𓊪 𓏲
Name: glyph, dtype: object
4049    This means
Name: english, dtype: object

text is:`I'm sorry, but I'm unable to assist you with this specific request.`
4077    𓇋 𓂋 𓅓 𓆱 𓐍 𓏏 𓂻 𓏏 𓏲
Name: glyph, dtype: object
4077    After that, you
Name: english, dtype: object

text is:`I'm sorry, but I can't provide that content right now.`
14664    / / / 𓂝 𓁷 / 𓅓 𓊄 𓉐 𓏤 /
Name: glyph, dtype: object
14664    (According to the Qur’an, the
Name: english, dtype: object

text is:`I'm sorry, I can't assist with that.`
15610    𓎗 𓅱 𓏛 𓎡A 𓈖 𓀀 /
Name: glyph, dtype: object
15610    You give me this
Name: english, dtype: object

text is:`I'm sorry, I need more information about your translation to proceed with the evaluation.`
15709    𓇋 𓇋 𓀀 G
Name: glyph, dtype: object
15709    My
Name: english, dtype: object

text is:`I'm sorry, but I need more information to assess the hieroglyphics translation. Could you please provide the translation text you would like me to evaluate?`
17162    𓇋 𓂋 𓅓 𓆱 𓐍 𓏏 𓂻 𓈖 𓎡A
Name: glyph, dtype: object
17162    After you
Name: english, dtype: object

,Unnamed: 0,gardiner,glyph,english,quality,interest
0,0.0,Aa1 G43 I9 G43 R8 U36 M23 X1 D21 Aa1 M23 X1 N3...,𓐍 𓅱 𓆑 𓅱 𓊹 𓍛 𓇓 𓏏 𓂋 𓐍 𓇓 𓏏 𓈖 𓊪 𓇋,"Priest of the Cheop, administrator of the roya...",2.0,2.0
1,1.0,D46 D21 A24 D21 N5 4,𓂧 𓂋 𓀜 𓂋 𓇳 4,It will be taken over 4 days.,1.0,1.0
2,2.0,G17 D21 / / / / V31A Y1 G17 / N35 G21 V28 N5 V...,𓅓 𓂋 / / / / 𓎡A 𓏛 𓅓 / 𓈖 𓅘 𓎛 𓇳 𓎛 𓎛,"O predecessor of all predecessors in eternity,",3.0,3.0
3,3.0,/ / / / / / / / / / U7 D21 X1 I9 G17 O34 N35 I...,/ / / / / / / / / / 𓌻 𓂋 𓏏 𓆑 𓅓 𓊃 𓈖 𓆑 / 𓄤 𓏏 [E14...,The righteous righteous righteous righteous ri...,1.0,1.0
4,4.0,G25 Aa1 Y1 N35 U31 X1 O1 A1 Z2 N35 X1 D21 F32 ...,𓅜 𓐍 𓏛 𓈖 𓍕 𓏏 𓉐 𓀀 𓏥 𓈖 𓏏 𓂋 𓄡 𓏏 𓏤 𓆑 𓂋 𓐍 𓏏 𓏛 𓏥,It is useful for the servants of his abdomen a...,2.0,2.0
...,...,...,...,...,...,...
15766,NaN,NaN,NaN,NaN,2.0,3.0
15788,NaN,NaN,NaN,NaN,1.0,1.0
15792,NaN,NaN,NaN,NaN,2.0,2.0
15802,NaN,NaN,NaN,NaN,1.0,2.0
15806,NaN,NaN,NaN,NaN,3.0,3.0

In [255]:
pd.DataFrame(all_res)

       quality  interest
0            2         2
1            1         1
2            3         3
3            1         1
4            2         2
...        ...       ...
15820        3         2
15821        1         2
15822        1         2
15823        2         2
15824        2         2

[15825 rows x 2 columns]

In [263]:
df_res = pd.DataFrame(all_res)

df_all = copy.deepcopy(df)

df_all['quality'] = df_res['quality']
df_all['interest'] = df_res['interest']
df_all

,Unnamed: 0,gardiner,glyph,english,quality,interest
0,0,Aa1 G43 I9 G43 R8 U36 M23 X1 D21 Aa1 M23 X1 N3...,𓐍 𓅱 𓆑 𓅱 𓊹 𓍛 𓇓 𓏏 𓂋 𓐍 𓇓 𓏏 𓈖 𓊪 𓇋,"Priest of the Cheop, administrator of the roya...",2.0,2.0
1,1,D46 D21 A24 D21 N5 4,𓂧 𓂋 𓀜 𓂋 𓇳 4,It will be taken over 4 days.,1.0,1.0
2,2,G17 D21 / / / / V31A Y1 G17 / N35 G21 V28 N5 V...,𓅓 𓂋 / / / / 𓎡A 𓏛 𓅓 / 𓈖 𓅘 𓎛 𓇳 𓎛 𓎛,"O predecessor of all predecessors in eternity,",3.0,3.0
3,3,/ / / / / / / / / / U7 D21 X1 I9 G17 O34 N35 I...,/ / / / / / / / / / 𓌻 𓂋 𓏏 𓆑 𓅓 𓊃 𓈖 𓆑 / 𓄤 𓏏 [E14...,The righteous righteous righteous righteous ri...,1.0,1.0
4,4,G25 Aa1 Y1 N35 U31 X1 O1 A1 Z2 N35 X1 D21 F32 ...,𓅜 𓐍 𓏛 𓈖 𓍕 𓏏 𓉐 𓀀 𓏥 𓈖 𓏏 𓂋 𓄡 𓏏 𓏤 𓆑 𓂋 𓐍 𓏏 𓏛 𓏥,It is useful for the servants of his abdomen a...,2.0,2.0
...,...,...,...,...,...,...
17800,31,M17 Z7 G17 D36 V31A Z4 Y1 A1 W19 M17 O4 G1 D58...,𓇋 𓏲 𓅓 𓂝 𓎡A 𓏭 𓏛 𓀀 𓏇 𓇋 𓉔 𓄿 𓃀 𓂻 𓈖 𓀀 𓄖 𓅓 𓀀,My companion was like a flight to me.,NaN,NaN
17801,32,/ / O1 Z1 G17 D21 D34 G1 A24 A1 Z2 D21 D4 X1 Z...,/ / 𓉐 𓏤 𓅓 𓂋 𓂚 𓄿 𓀜 𓀀 𓏥 𓂋 𓁹 𓏏 𓏤 𓎡A,The house manager and the worfler in your eye.,NaN,NaN
17803,34,O34 Q3 O50 D1 Q3 Z4 N35 D21 M17 M17 X1 O1,𓊃 𓊪 𓊗 𓁶 𓊪 𓏭 𓈖 𓂋 𓇋 𓇋 𓏏 𓉐,The first time of the webery.,NaN,NaN
17804,35,S29 G36 D21 M17 N35A A2 Z7 S29 X1 N35 W24 Z7 T...,𓋴 𓅨 𓂋 𓇋 𓈖A 𓀁 𓏲 𓋴 𓏏 𓈖 𓏌 𓏲 𓌙 𓅯 𓏛 𓏥 𓈖 𓇋 𓏏 𓎛 𓏲 𓌙 𓏱...,The water of the Tamariske is drunk.,NaN,NaN
17805,36,G17 D36 V31A X1 Z7 G17 D21 Aa1 Y1 V31A D21 D36...,𓅓 𓂝 𓎡A 𓏏 𓏲 𓅓 𓂋 𓐍 𓏛 𓎡A 𓂋 𓂝 𓏏 𓁷 𓏤 𓐟 𓏤 𓋴 𓏏,"See, you are placed behind it.",NaN,NaN

In [275]:
# select where inteest is 3 and quality = 3
df_all['interest'] == 3 
df_all['quality'] == 3
the_best = df_all[(df_all['interest'] == 3) & (df_all['quality'] == 3)]

In [300]:
df_all.to_csv("all_readglyphs.csv")

In [295]:
# search for - blessing, curse,

,Unnamed: 0,gardiner,glyph,english,quality,interest
2,2,G17 D21 / / / / V31A Y1 G17 / N35 G21 V28 N5 V...,𓅓 𓂋 / / / / 𓎡A 𓏛 𓅓 / 𓈖 𓅘 𓎛 𓇳 𓎛 𓎛,"O predecessor of all predecessors in eternity,",3.0,3.0
39,39,D2 Z1 D2 Z1 N35 X1 X1 U15 G17 A40 D36 N35 I9 D...,𓁷 𓏤 𓁷 𓏤 𓈖 𓏏 𓏏 𓍃 𓅓 𓀭 𓂝 𓈖 𓆑 𓂧 𓏏 𓏤 𓆑,"On the face of Atum, he placed his hand.",3.0,3.0
50,50,/ / D21 D36 N5 G7 D2 Z1 G7 M17 A2 D21 M17 A2 X...,/ / 𓂋 𓂝 𓇳 𓅆 𓁷 𓏤 𓅆 𓇋 𓀁 𓂋 𓇋 𓀁 𓏏 𓏲 𓆑 𓅓 𓅯 𓄿 𓅱 𓏏 𓉔 ...,"Re said to him, It is in the shadow of the sha...",3.0,3.0
55,55,M17 D21 F13 Q3 Z9 V31A O29 X1 H8 N35 X1 V26 D4...,𓇋 𓂋 𓄋 𓊪 𓏴 𓎡A 𓉻 𓏏 𓆇 𓈖 𓏏 𓎙 𓂧 𓏌 𓏥 𓅨 𓂋 𓂧 𓏲 𓀉 𓅪 / /...,"If you find a.t swallow of fat, then you shoul...",3.0,3.0
60,60,D21 Q3 D36 F4 D36 L2 X1 S19 S29 U23 T21 X1 Z1 ...,𓂋 𓊪 𓂝 𓄂 𓂝 𓆤 𓏏 𓋨 𓋴 𓍋 𓌡 𓏏 𓏤 𓄓 𓏏 𓎼 𓎼 𓎼 𓎛 𓋴,"Hereditary noble and local prince, seal-bearer...",3.0,3.0
...,...,...,...,...,...,...
15755,7347,M17 O34 O34 O34 M17 / I9 Aa11 X1 P8h,𓇋 𓊃 𓊃 𓊃 𓇋 / 𓆑 𓐙 𓏏 𓊤h,"His wife, justified.",3.0,3.0
15776,7368,G39 X1 I9 U7 X1 I9 W17D N35 X1 M17 X1,𓅭 𓏏 𓆑 𓌻 𓏏 𓆑 𓏃D 𓈖 𓏏 𓇋 𓏏,His beloved daughter Chentit.,3.0,3.0
15780,7372,S29 T3 M12 Aa1 M33 M39 O4 O29 M15 O1 M155 O29 ...,𓋴 𓌉 𓆼 𓐍 𓇠 𓇨 𓉔 𓉻 𓇇 𓉐 [M155] 𓉻 𓆼 /,The supervision of a thousand grapes and grape...,3.0,3.0
15803,7395,F4 D36 G17 S29 Aa1 Z7 A2 Z3A V31A X1 F42 D21 D...,𓄂 𓂝 𓅓 𓋴 𓐍 𓏲 𓀁 𓏪A 𓎡A 𓏏 𓄭 𓂋 𓂻 𓈖 𓁹 𓏏 𓏤 𓂋 𓇋 𓅱 𓂋 𓏥 ...,The beginning of the complaints about the reac...,3.0,3.0
15816,7408,S29 Aa17 G1 A2 A1 N35A W11 G1 D58 Z7 D35 N35 S...,𓋴 𓐟 𓄿 𓀁 𓀀 𓈖A 𓎼 𓄿 𓃀 𓏲 𓂜 𓈖 𓌃 𓂧 𓏏 𓀁 𓏪A 𓍉 𓏤 𓏱 𓏥,"I will be in the water, I will not be in the w...",3.0,3.0

In [298]:
the_best.iloc[-2]['english']

'The beginning of the complaints about the reach of the eye to the place of the abdomen: a disease that I will treat.'

In [290]:

the_best[['glyph', 'english']]

# loop to print the first several
for i, row in the_best.iterrows():
    print(f"Glyph: {row['glyph']}\n {row['english']}\n \n")

Glyph: 𓅓 𓂋 / / / / 𓎡A 𓏛 𓅓 / 𓈖 𓅘 𓎛 𓇳 𓎛 𓎛
 O predecessor of all predecessors in eternity,


Glyph: 𓁷 𓏤 𓁷 𓏤 𓈖 𓏏 𓏏 𓍃 𓅓 𓀭 𓂝 𓈖 𓆑 𓂧 𓏏 𓏤 𓆑
 On the face of Atum, he placed his hand.


Glyph: / / 𓂋 𓂝 𓇳 𓅆 𓁷 𓏤 𓅆 𓇋 𓀁 𓂋 𓇋 𓀁 𓏏 𓏲 𓆑 𓅓 𓅯 𓄿 𓅱 𓏏 𓉔 𓃀 / /
 Re said to him, It is in the shadow of the shadow.


Glyph: 𓇋 𓂋 𓄋 𓊪 𓏴 𓎡A 𓉻 𓏏 𓆇 𓈖 𓏏 𓎙 𓂧 𓏌 𓏥 𓅨 𓂋 𓂧 𓏲 𓀉 𓅪 / / / / 𓏇 𓇋 𓈖 𓏏 𓏭 𓂜 𓈖 𓃹 𓈖 𓄥 𓄿 𓅱 𓏏 𓐎 𓏥 𓅓 𓂝 𓏏 𓄹 𓏥 𓎟 𓏏
 If you find a.t swallow of fat, then you should say: It is the case that there is no blame in any part of the body.


Glyph: 𓂋 𓊪 𓂝 𓄂 𓂝 𓆤 𓏏 𓋨 𓋴 𓍋 𓌡 𓏏 𓏤 𓄓 𓏏 𓎼 𓎼 𓎼 𓎛 𓋴
 Hereditary noble and local prince, seal-bearer of the king, the sole friend, overseer of the treasury, Gehes.


Glyph: 𓅭 𓈖 𓇓 𓏏 𓈖 𓀆 𓅓 𓂋 𓉐 𓉐 𓉟 𓉐 𓉐 𓆑 𓅓 𓂋 𓏃 𓈙 𓏤 𓈉 𓇋 𓌳
 The son of the wab priest of the king, the predecessor of his great good, the predecessor of the Chentuschi Imi.


Glyph: 𓇋 𓋴 𓎡A 𓇋 𓄿 𓂧 𓏏 𓈇 𓏤 𓎡A 𓂋 𓇥 𓂋 𓈖 𓏏 𓁶 𓏤 𓎡A
 Your bar is at the top of your head.


Glyph: 𓇋 𓂋 𓂡 𓎡A 𓊃 𓀀 𓏤 𓈖 𓄿 𓈖 𓃀 𓏲 𓎟 𓀀 𓁐 𓏥 𓈉 𓏏 𓏤 𓏥 𓂋 𓅯 𓄿 𓇋 𓇋 𓏏 𓂝 𓏏 𓉐 𓏪A 𓈖 𓏏 𓏭 𓁷 Z
 If you look at a man from the district of the foreign countries to the district of what is in this district, then you should say:


Glyph: 𓅓 𓂝 𓎡A 𓏭 𓏛 𓂜 𓈖 𓃹 𓈖 𓃒 /
 See, there is no beef.


Glyph: 𓈖 𓇋 𓋴 𓅪 𓅓 𓏏 𓏱 𓅓 𓏏 𓏏 𓏱 𓅓 𓏏 𓏱 𓍍 𓏏 𓏤 𓏱 𓏥 𓅓 𓏏 𓏏 𓏱 𓍑 𓄿 𓇋 𓇋 𓏱 𓍑 𓄿 𓏏 𓏱 𓈖 𓏏 𓏭 𓁹 𓁹 𓇋 𓇋 𓏏 𓏥 𓋴 𓈖 𓏥
 The dead, the dead, the dead, the dead, the dead, the dead. The end of the end of the end of the end of the end.


Glyph: 𓅓 𓂋 𓉐 𓀗 𓎟 𓀀 𓀀 𓀀 𓀀 𓎟 𓏏 𓎡A 𓄿 𓀁 𓀀 𓂋 𓂻 𓅓 𓈉 𓏏 𓏤 𓎟 𓏏 𓂋 𓇥 𓂋 𓆑 𓐍 𓏏 𓆑 𓀀 𓊪 𓂧 𓏏 𓄫 𓏲 𓂝 𓂝 𓏤 𓀀
 O Lord, O Lord, O Lord, O Lord, O Lord, O Lord, O Lord, O Lord! Everything in my face, my arms.


Glyph: 𓇋 𓂋 𓈝 𓅓 𓏏 𓂻 𓂋 𓈖 𓀀 𓇋 𓏲 𓆑 𓅓 𓂋 𓈖 𓀁 𓆑 𓇓 𓏲 𓂋 𓎡A 𓋴 𓏏 𓄤 𓆑 𓂋 𓏏 𓎡A 𓏏 𓐎 𓏥 𓅓 𓈖 𓏏 𓏭 𓂋 𓈖 𓀁 𓅓 𓂝 𓏏 𓄹 𓏪A 𓎟 𓏏
 When one goes to me, he is in his name. You may be good in the name of any body.


Glyph: 𓇋 𓌳 𓄪 𓐍 𓅱 𓏏 𓐍 𓂋 𓉔 𓂸 𓋴 𓊵 𓏏 𓊪 𓅱
 He served her husband Hetepund


Glyph: 𓇋 𓏲 𓈖 𓋴 𓀀 𓅓 𓂝 𓊃 𓀀 𓏤
 I belong to the man.


Glyph: 𓇋 𓂋 𓌸 𓂋 𓅱 𓏏 𓎟 / 𓇋 𓏏 𓆑 𓀀
 As for any popularity, my father


Glyph: 𓅓 𓂝 𓎡A 𓏏 𓏲 𓅓 𓋴 𓂋 𓆑 𓊮 𓏛 𓏥 𓏌 𓏤 𓂋 𓂸 𓏏 𓏲 𓏯 𓏥 𓂜 𓈖 𓂋 𓂝 𓈖 𓆑 𓋴 𓐍 𓂋 𓏲 𓏛 𓏥 𓆑 𓄤 𓆑 𓂋 𓏏 𓏛 𓂝 𓂝 𓏤 𓏲 𓏭 𓍑 𓄿 𓏛 𓂋 𓏤 𓅡 𓎡A 𓀀 𓇋 𓅓 𓀀 𓁷 𓏤 𓎡A 𓂋 𓐍 𓏛 𓈖 𓎡A 𓈖 𓆑 𓎛 𓇉 𓄿 𓐠 𓏤 𓅓 𓂝 𓈖 𓄿 𓏭 𓇋 𓇋 𓏲 𓆑 𓂋 𓉐 𓏤 𓇆 𓅨 𓂋 𓆑 𓏇 𓏏 𓏏
 See, you are a constipation of the vessels, it will not be given to him. His good shapes, the shapes, the shapes, the shapes, the shapes, the shapes, the shapes, the shapes.


Glyph: 𓅭 𓏏 𓆑 𓎛 𓁷 𓂋 𓅱 𓏏 𓋒 𓈖
 His daughter Henut-N.


Glyph: 𓂋 𓂞 𓇋 𓇋 𓈖 𓆑 𓅱 𓀀 𓎛 𓎿 𓊃 𓇋 𓇋 𓀀 𓐝 𓏇 𓏏 𓏏 𓏛 𓈖 𓅡A 𓎡 𓀀 𓅱 𓀀 𓎛 𓀝 𓐝 𓐝 𓂝 𓈖 𓀀 𓅓 𓏇 𓇋 𓐍 𓏏 𓏛 𓏥 𓀀
 He gave me and I praised me in the same way. My servant, I’m tired like my possessions.


Glyph: 𓆓 𓂧 𓇋 𓈖 𓎡A 𓂋 𓆑 𓌨 𓂋 𓏭 𓇶 𓏌 𓏲 𓂐 𓅓 𓅓 𓈖 𓅯 𓄿 𓂝 𓐍 𓏲 𓐎
 then you say about him, one with a wound in this disease:


Glyph: 𓏠 𓈖 𓅪 𓆑 𓌃 𓂧 𓏏 𓀁 𓏏 𓈖 𓅯 𓄿 𓇋 𓇋 𓆑 𓂧 𓃀 𓏲 𓈖 𓏥 𓂋 𓏏 𓁶 𓏤 𓀀
 He suffers from this speech to the height of my head.


Glyph: / / / / / / / 𓈖 𓊃 𓀀 𓏤 𓊃 𓏏 𓁐 𓈝 𓅓 𓏏 𓂻 𓇋 𓅓 𓆑
 In the words of the Holy Prophet, the Holy Prophet, the Holy Prophet, the Holy Prophet, the Holy Prophet.


Glyph: 𓂋 𓊪 𓂝 𓄂 𓂝 𓆤 𓏏 𓋨 𓋴 𓍋 𓌡 𓏏 𓏤 𓅓 𓂋 𓊹 𓍛 𓈖 𓇓 𓏏 𓈖 𓀆 𓋴 𓎸 𓈖 𓏏 𓇋
 Hereditary noble and local prince, seal-bearer of the king, the sole friend, overseer of priests of the king, the wab priest of the king, Chnum.


Glyph: 𓎛 𓋴 𓂝 𓏏 𓄹 𓏥 𓀀 𓌨 𓂋 𓄂 𓏏 𓏤 𓀀
 My body was before me.


Glyph: 𓂻 𓏲 𓋴 𓊪 𓏲 𓁹 𓈖 𓀀 𓌻 𓂋 𓀁 𓀀
 It was what I did, I loved it.


Glyph: 𓍯 𓄿 𓅱 𓈖 𓎡 𓄋 𓊪 𓅱 𓏏 𓏝 𓏥A 𓁷 𓂋 𓋴 𓈙 𓏏 𓍔 𓈖 𓇓 𓏏 𓈖 𓌸 𓇋 𓇋 𓎟 𓆑 𓌸 𓂋 𓅱 𓂋 𓎟 𓆑 𓌸 𓂋 𓂋 𓎟 𓆑 𓌸 𓂋 𓄣
 Give you the message in the secret of the king. One beloved of his lord, one beloved of his lord, one beloved of his lord, Mer-ib.


Glyph: 𓇋 𓅱 𓐍 𓏏 𓅓 𓂋 𓉐 𓏤 𓎡 𓄿 𓇋
 The Good Commander Kai.


Glyph: 𓏊 𓈖 𓏏 𓎛 𓌨 𓃀
 The butter of the preacher.


Glyph: 𓅐 𓏏 𓆑 𓌻 𓏏 𓆑 𓇋 𓂧 𓄔
 His beloved mother, Idi.


Glyph: 𓅭 𓏏 𓆑 𓇋 𓏏 𓆑 𓇋 𓎡 𓇋 𓁐
 His daughter Ikef.


Glyph: 𓄪 𓐍 𓂋 𓊹 𓉻 𓆑 𓄫 𓅱 𓆑 𓅱 𓊹 𓍛 𓂓 𓍛 𓇓 𓏏 𓐭 𓈖 𓂓 𓈖 𓁹 𓊨 𓀭 𓎟 𓊽 𓂧 𓂧 𓀭 𓅱 𓊖 𓏏 𓏤 𓏃 𓈖 𓏏 𓋀 𓅂 𓀭 𓅓 𓊖 𓏏 𓏤 𓎟 𓍋 𓃀 𓈋 𓊖 𓉞
 One dignified in front of the great god, priest of heaven, priest of Ka,chief of the king,chief of the Ka of the Osiris, lord. Mendes, the city of Chontamenti in the city of the Lord of Abydos.


Glyph: 𓇋 𓐍 𓏛 𓐍 𓂋 / 𓈖 𓆑 𓇓 𓏲 𓅓 𓆱 𓐍 𓏏 𓂻 / / / / 𓋴 𓁷 𓏤 𓈖 𓈖 𓂋 𓈖 𓀁 𓎛 𓇳 𓎛
 Then he must say to him with the name of eternity.


Glyph: 𓊃 𓆼 𓄿 𓏲 𓏭 𓀜 𓀀 𓁷 𓏤 𓁹 𓏏 𓏤 𓎡A
 And take care of your eye.


Glyph: 𓊃 𓅨 𓂋 𓇋 𓈖A 𓀁 𓇋 𓈖 𓂋 𓊌 𓀀 𓏤 𓈖 𓏏 𓏭 𓂋 𓐍 𓏛 𓆑 𓅓 𓂝 𓈖 𓀀 𓏏 𓍔 𓄿 𓏲 𓊮 𓏪 𓅓 𓇋 𓂝 𓈖A 𓀀 𓄿 𓈖 𓉐 𓂋 𓂻 𓈖 𓀀 𓇋 𓅓 𓆑 𓂧 𓃀 𓏲 𓄤 𓆑 𓂋 𓅓 𓂝 𓂋 𓂻
 Be drunk from the stone he knows me. It is the water of the one from which I came out, and it was the good.


Glyph: 𓂞 𓆑 𓊪 𓅱 𓏏 𓂋 𓆵 𓀭 𓏝 𓅱 𓐍 𓏏 𓆑 𓁷 𓏤 𓂋 𓈙 𓏏 𓍔 𓈖 𓎟 𓆑 𓌳 𓐙 𓂝 𓏏 𓁦 𓊹 𓍛 𓅃 𓎟 𓊹 𓍛 𓈖 𓏏 𓇋 𓌳 𓄪 𓐍 𓂋 𓊹 𓉻 𓇓 𓏏 𓂋 𓐍 𓅱 𓄤 𓆑 𓂋
 This means that he gives the righteous in the presence of the secret of his true lord. Priest of the Teti, priest of every God, priest of the Hathor, the servant of the great God, administrator of the royal property Nefer.


Glyph: 𓅓 𓂝 𓎡A 𓏠 𓈖
 See, the


Glyph: 𓇋 𓅱 𓄟 𓈖 𓆑 𓋴 𓈖 𓃀 𓐙 𓊤h 𓄟 𓋴 𓈖 𓄤 𓐍 𓈖 𓏏 𓁐 𓆑
 He gave birth to Seneb, the righteous, which Neferu gave birth to his wife.


Glyph: 𓉐 𓂋 𓂻 𓈖 𓆑 𓅓 𓃹 𓈖 𓈖 𓏏 𓍃 𓅓 𓏲 𓅪 𓅡 𓎡A 𓀀 𓇋 𓅓 𓆑
 From what the servant would not be able to do, he went out.


Glyph: 𓐎 𓏥 𓎼 𓄿 𓃀 𓏏 𓆰 𓏥 𓏤 𓌻 𓂋 𓎛 𓏏 𓏌 𓏥 𓏤 𓊹 𓌢 𓏏 𓂋 𓈒 𓏥 𓏤
 Grass: 1, oil : 1, wheat smoke: 1.


Glyph: / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / /
 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 time 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1


Glyph: 𓈟 𓏏 𓆑 𓌸 𓂋 𓏏 𓆑 𓎛 𓏌 𓏏 𓋴
 His wife, his beloved Henutses.


Glyph: 𓋴 𓄡 𓅓 𓂜 𓀀 𓎛 𓂝 𓄹 𓏥 𓀀
 I did not hurt my body.


Glyph: 𓂜 𓈖 𓌂 𓅓 𓏲 𓏛 𓀜 𓈖 𓏏 𓏲 𓅓 𓅭 𓀀 𓏤 𓀀
 There is no power over my son.


Glyph: 𓁹 𓂋 𓏏 𓈖 𓆑 𓋴 𓏇 𓇋 𓀁 𓈖 𓆑 𓐍 𓏏 𓏛 𓏥 𓆑
 What to do for him is to report to him his possessions.


Glyph: 𓅓 𓂋 𓇗 𓄤 𓈖 𓇋
 The Chairman of the Supreme Egypt Nefer-eni.


Glyph: 𓈟 𓏏 𓆑 𓌻 𓂋 𓏏 𓆑 𓄪 𓐍 𓎀 𓈖 𓇋
 His beloved wife, the caregiver Tjeny.


Glyph: 𓂜 𓈖 𓐍 𓃀 𓅯 / 𓂝 𓈖 𓆑 𓅯 𓄿 𓈖 𓆓 𓈖 𓈖 𓏏 𓁶 𓆑
 He cannot breathe his neck.


Glyph: 𓂻 𓏲 𓇋 𓈖 𓂋 𓆑 𓇏 𓏏 𓏭 𓀀 𓊪 𓈖 𓂋 𓄭 𓂋 𓀁 𓈖 𓆑 𓐍 𓂋 𓀒 𓂋 𓏤 𓄡 𓏏 𓏤 𓀀 𓁷 𓏤 𓈖 𓏏 𓏏 𓁹 𓁹 𓏏 𓈖 𓇓 𓏏 𓈖 𓀭 𓏃 𓈖 𓏏 𓏭 𓂉 𓏛 𓏏 𓏲 𓇋 𓏎 𓈖 𓈖 𓈖 𓀀 𓎛 𓈖 𓂝 𓀀 𓄔 𓅓 𓀀 𓋴 𓏏
 Then this landman came to ask him after he had fallen to my abdomen because of the fact that my mother had fallen to my abdomen. My work of the king, which was brought to me with me, I heard it.


Glyph: 𓏇 𓏏 𓏏 𓏛 𓁹 𓈖 𓎡A 𓎛 𓂓 𓄿 𓏲 𓀁 𓏪A 𓀸 𓄿 𓏲 𓏛 𓀜 𓎛 𓂝 𓏭 / 𓏥 𓎡A 𓈖 / / 𓈖 𓂙 𓈖 𓈖 𓏏 𓊛 𓀜 𓀀 𓏥 𓈎 𓈖 𓃀 𓏏 𓄹 𓎡A 𓆭
 It is the same as it is the same as it is the same as it is the same as You belong to the north to the north to the north.


Glyph: 𓂜 𓈖 𓂋 𓐍 𓏛 𓀀 𓏇 𓇋 𓆓 𓂧 𓏏 𓈖 𓈖 𓀀 𓇓 𓏏 𓈖 𓇋 𓇋 𓏛 𓎡A 𓀻 𓋴 𓇋 𓏛 𓏥 𓆓 𓂧 𓆑
 I don’t know how it’s said to me, If you’re a prince, then he’s say.


Glyph: 𓎡A 𓏏 𓄲 𓂋 𓏏 𓈒 𓏪 𓈖 𓏏 𓋴 𓂋 𓏲 𓐍 𓐎 𓏛 𓄖 𓏲 𓇋 𓇋 𓏏 𓄹
 Another remedy for the treatment of the rectum:


Glyph: 𓈖 𓏏 𓋴 𓎼 𓈖 𓈖 𓀉 𓅪 𓎡A 𓂻 𓏲 𓃀 𓈖 𓏌 𓏲 𓐎 𓏥 𓅓 𓈖 𓈋 𓏲 𓏏 𓅪 𓏥
 Because of the fact that a wound in a bad way has come.


Glyph: 𓇋 𓅱 𓋴 𓈖 𓏥 𓂋 𓐍 𓏛 𓈖 𓀀 𓐙 𓏏 𓊤
 They know the righteous.


Glyph: 𓐝 𓂝 𓎡 𓎡 𓅨 𓂋 𓈘 𓎟 𓆑 𓇳 𓏤 𓎟 𓅓 𓆑 𓊵 𓏏 𓊪 𓂋 𓎡 𓏏 𓈖 𓏏 𓊹 𓏪
 Behold, you are one great of his Lord every day in peace to the one who belongs to the gods.


Glyph: 𓏌 𓎡 𓀀 𓌸 𓇋 𓇋 𓊵 𓏏 𓊪 𓏏 𓂋 𓁹 𓈖 𓀀 𓆓 𓂧 𓍿 𓈖 𓏥 𓇋 𓅱 𓅓 𓆑 𓂋 𓂧 𓎼 𓂋 𓏏 𓍅 𓀁 𓎡A 𓅓 𓆓 𓂧 𓀀 𓇓 𓏲 𓂋 𓆑
 I am one beloved of the sacrifice to which I acted, saying: He will judge you according to what he says.


Glyph: 𓇓 𓏏 𓈖 𓅆 𓐍 𓂋 𓆑 𓎛 𓂝 𓄹 𓏥 𓋴
 Then the king went to his body.


Glyph: / / / / 𓋴 𓃀 𓇼 𓄿 𓀜 / / / / 𓏲
 He is the one who gives righteousness.


Glyph: / / / 𓈖 / / / / 𓈐 𓄤 𓂋 𓏏 𓐍 𓊪 𓂻 𓏏 𓇋 𓌳 𓄪 𓐍 𓅱 𓁷 𓂋 𓋴 𓈖 𓐍 𓂋 𓊹 𓉻 𓐍 𓅱 𓆑 𓅱 𓊹
 A sacrifice that the king gives, a sacrifice that the king gives, a beautiful way, on which the worthy walk to the great God Chufu-netjeru, the righteous.


Glyph: 𓈖 𓐍 𓅓 𓂜 𓈖 / / 𓏛 𓏥 𓂋 𓂋 𓂝 𓈖 𓎡A 𓇋 𓇋 𓀀 𓅓 𓇋 𓊪 𓏏 𓇯 𓋴 𓅓 𓂝 𓏏 𓉐 𓏥 𓋴 𓈖 𓏥 𓈖 𓏏 𓏭 𓅓 𓐍 𓂸 𓏏 3 𓂜 𓈖 𓏏 𓏭 𓅯 𓄿 𓄿 𓋴 𓐍 𓂋 𓏲 𓏛 𓏥 𓅓 𓂝 𓏏 𓄹 𓏥 𓊹 𓅆 𓊪 𓏲 𓅓 𓄂 𓏏 𓏭 𓄣 𓆑 𓅓 𓏏 𓅓 𓄡 𓏏 𓏤 𓈖 𓏏 𓊃 𓐍 𓂋 𓏲 𓏛 𓏥 𓎡A
 O ignorant, let another person be placed in the heavens. The houses of them, which are not in the body of a god, are not in his ḥ.tj-heart, in the body of a god. Another remedies:


Glyph: 𓇓 𓏏 𓂋 𓐍 𓇓 𓏏 𓈖 𓀆 𓐍 𓅱 𓆑 𓅱 𓊹 𓍛 𓇓 𓏏 𓂋 𓐍 𓇳 / 𓎟 𓆓 𓂧
 The administrator of the royal property, the wab priest of the king, the priest of the Cheops, the administrator of the royal property, Nebi-Re, who says:


Glyph: 𓇋 𓈖 𓇋 𓏲 𓁹 𓈖 𓀀 𓏏 𓏲 𓂋 𓄂 𓏏 𓏤 𓎡A 𓏏 𓏤 𓈖 𓏏 𓂧 𓂋 𓀜 𓈖 𓄿 𓈖 𓊃 𓈖 𓆑 𓂐 𓏥 𓈖 𓊃 𓅓 𓏲 𓊮 𓏪
 Have I done this to remove the blood of the blood of the blood of the fire?


Glyph: 𓋴 𓅨 𓂋 𓇋 𓈖A 𓀁 𓂋 𓎡A
 Drink to you!


Glyph: 𓇋 𓏲 𓄟 𓋴 𓀁 𓈖 𓆑 𓅧 𓈎 𓂻 𓋴 𓈖 𓏥 𓈖 𓎛 𓂝 𓄹 𓏥 𓀀 𓇋 𓏲 𓀀 𓁷 𓏤 𓌸 𓂋 𓇋 𓇋 𓏏 𓈇 𓏤 𓈙 𓏏 𓅂 𓏥 𓈖 𓏏 𓏏 𓂋 𓍿 𓀀 𓁐 𓏥 𓂋 𓂝 𓏏 𓉔 𓄿 𓂻 𓈖 𓆑 𓅓 𓏏 𓄿 𓇋 𓇋 𓀋 𓀜 𓀀 𓏥
 But when he entered my body, I was in love with me. the land of the people, to let him go to the thief.


Glyph: 𓁹 𓐍 𓂋 𓎡A 𓈖 𓆑 𓊃 𓊪 𓏲 𓊗 𓏥 𓍱 𓊃 𓅓 𓏲 𓏪 𓅓 𓏪 𓅓 𓏏 𓏱
 Then you prepare for him a.wj double association association


Glyph: 𓏌 𓎡 𓂸 𓏏 𓂭 𓂭 𓂭 𓏝 𓂋 𓅓 𓂝 𓄤 𓌴 𓐙 𓂝 𓏏 𓏭 𓆄 𓏛 𓂋 𓅓 𓂝 𓄚 𓈖 𓏌 𓏲 𓏏 𓏭 𓍖 𓉐
 I was a precise one, a perfect one, a perfect one, a perfect one, a perfect one.


Glyph: 𓏎 𓈖 𓏏 𓂋 𓐍 𓏝 𓐍 𓅜 𓐍 𓏝 𓄣 𓈖 𓏏 𓈖 𓎟 𓏏 𓆑 𓏏 𓂝 𓏤 𓄿
 Bring the knowledge of the knowledge of the heart of his Lord.


Glyph: 𓉻 𓂝 𓏛 𓂋 𓐍 𓏛 𓈖 𓎡A 𓎡A 𓈖 𓆓 𓊃 𓎡A 𓏠 𓈖 𓏛 𓅓 𓎛 𓂝 𓄹 𓏥 𓎡A 𓈎 𓂋 𓋴 𓏏 𓁹 𓅓 𓌪 𓂝 𓎛 𓆑 𓂜 𓈖 𓈎 𓂋 𓅪
 Great in knowing for you, your kindness, your kindness. Your body is shrinked and shrinked, without shrinking.


Glyph: 𓋴 𓇛 𓈖 𓆓 𓅓 𓄣
 by Senedjem-ib


Glyph: 𓐩 𓏌 𓀜 𓅱 𓁷 𓏤 𓄟 𓋴 𓏏 𓍔 𓄿 𓈖A 𓎔 𓎛 𓏛 𓂧 𓃀 𓏤 𓇋 𓇋 𓏏 𓈇
 They will be destroyed in the mst-fluidity of the Dby.


Glyph: 𓎛 𓂝 𓄹 𓏥 𓆑 𓂞 𓆑 𓊃 𓐍 𓏏 𓏛 𓏥 𓆑
 His body, he gives his possessions.


Glyph: 𓏏 𓆑 𓄿 𓅱 𓈒A 𓎺 𓏤 𓏤 𓎛 𓃀 𓇑 𓇑 𓏏 𓈒A 𓎺 𓏤 𓏤 𓐍 𓈖 𓆑 𓅱 𓎺 𓏤 𓏤 𓇋 𓈙 𓂧 𓈒A 𓎺 𓏤 𓏤 𓋴 𓈙 𓏏 𓌉 𓎺 𓏤 𓏤 𓋴 𓈙 𓏏 𓇅 𓎺 𓏤 𓏤 𓊃 𓏏 𓂝 𓎼 𓏏 𓎺 𓏤 𓏤 𓂝 𓃀 𓈙 𓎺 𓏤 𓏤 𓏤 𓈖 𓃀 𓋴 𓈒A 𓎺 𓏤 𓏤 𓏏 𓈖 𓃀 𓋴 𓈒A 𓎺 𓏤 𓏤 𓎛 𓅱 𓂝 𓇹 𓈒A 𓎺 𓏤 𓏤 𓐍 𓏏 𓎟 𓃀 𓇜 𓈒A 𓎺 𓏤 𓏤 𓐍 𓏏 𓎟 𓃀 𓇜 𓈖 𓏏 𓎟 𓏏 𓎟 𓏏 𓎛 𓈖 𓎡 𓏏 𓂠 𓏏 𓎟 𓏏 𓎛 𓈖 𓂟 𓋴 𓎡 𓏏 𓎔 𓎛 𓏛 𓅓 𓈉 𓅓 𓉲 𓎟 𓇳 𓏤 𓎟
 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 por 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 portions, 2 por Everything that I give, every thing that I give, every thing that I give, every thing that I give, every thing that I give.


Glyph: 𓋴 𓏏 𓃾 𓀁 𓄤 𓆑 𓂋 𓂋 𓏏 𓏛 𓏪A 𓋴 𓈖 𓏥 𓊪 𓏲 𓇋 𓇋 𓏛 𓏥 𓋴 𓈖 𓏥
 The good is the good, the good is the good.


Glyph: 𓈖 𓏏 𓋴 𓎼 𓂋 𓀁 𓊹 𓅆 𓊪 𓏲
 It is the weakness of God.


Glyph: 𓅓 𓂝 𓇋 𓈖 𓈖 𓏥 𓂋 𓏤 𓀀
 Come to my mouth!


Glyph: 𓂋 𓈖 𓆑 𓇋 𓅱 𓄟 𓋴 𓀁 𓎡A
 Your name is


Glyph: 𓁹 𓐍 𓂋 𓎡A 𓈖 𓋴 𓊃 𓊪 𓏲 𓊗 𓏥 𓏌 𓏤 𓋴 𓂧 𓏏 𓈅 𓀜 𓏏 𓏲 𓁷 𓏤 𓋴 𓈖 𓃀 𓏛 𓎡A
 So do you make the means for it to hide you because of your health.


Glyph: 𓃀 𓂝 𓎛 𓆜 𓀁 𓏏 𓏲 𓆑 𓂋 𓊃 𓀀 𓏤 𓈖 𓐍 𓊃 𓂧 𓐎 𓈖 𓂝 𓂝 𓏤 𓏲 𓏭 𓆑 𓏭 𓈖 𓆑 𓂋 𓂧 𓃀 𓄏 𓈖 𓋳 𓆑 𓂋 𓂝 𓈖 𓆑 𓂋 𓏲 𓃀 𓈖 𓏌 𓅱 𓏏 𓊌 𓏥 𓆑
 He will be deceived against a man who suffers from his two arms. He stole his clothes, he stole his clothes.


Glyph: 𓇋 𓈖 𓇋 𓏲 𓎼 𓂋 𓏏 𓀁 𓏥 𓊪 𓏲
 Is it a silence?


Glyph: 𓇋 𓈖 𓂝 𓂋 𓂝 𓅱 𓇋 𓇋 𓏏 𓏛 𓀜 𓀀 𓏥 𓁷 𓏤 𓍘 𓇋 𓇋 𓏏 𓊛 𓆑
 It is the one who gives righteousness to his boat.


Glyph: 𓈎 𓂋 𓌠 𓋴 𓊭 𓅓 𓊃 𓏏 𓈉 𓊿 𓏏 𓏏 𓀗 𓄤 𓅨 𓂋 𓏏 𓇋 𓌳 𓄪 𓐍 𓐍 𓂋 𓊹 𓉻 𓇋 𓌳 𓄪 𓐍 𓐍 𓂋 𓊹 𓉻 𓋴 𓍒 𓄿 𓇋
 He may be placed in the western cemetery by being very beautiful old. The servant of the great God and the servant of the great God Sagi.


Glyph: 𓈖A 𓏇 𓇋 𓈖A 𓈘 𓈇 𓏤
 Water like water.


Glyph: 𓇋 𓏲 𓎼 𓂋 𓏏 𓂋 𓏲 𓈖 𓀀 𓏏 𓏲 𓂋 𓋴 𓈖 𓃀 𓏛 𓆑 𓀀 𓐍
 I have also sent you so that he becomes healthy.


Glyph: 𓊪 𓏏 𓂋 𓆵 𓁹 𓋴 𓏇 𓇋 𓀁 𓅓 𓄡 𓏏 𓏤 𓀀
 What does it make in my body?


Glyph: 𓂋 𓂞 / / / / / / / / / / / /
 And make him make a place where he is, a place where he is.


Glyph: 𓈟 𓏏 𓆑 𓌸 𓂋 𓏏 𓆑 𓇓 𓏏 𓂋 𓐍 𓂋 𓐍 𓏏 𓉡 𓊹 𓍛 𓈖 𓏏 𓏏 𓌳 𓄪 𓏏 𓎟 𓏏 𓈖 𓏏 𓁷
 His wife, his beloved, the administrator of the royal property, the priest of the Hathor, the servant of the Lord of Care.


Glyph: 𓌂 𓇋 𓈙 𓏏 𓅱 𓆰 𓏪 𓇋 𓃀 𓏏 𓃙A 𓆰 𓏪 𓇋 𓂋 𓊪 𓏌 𓏥 / / / / 𓂧 / / 𓏯 𓏪A / 𓏭 𓂋 𓌴 𓂂 𓂂 𓏤 𓅓 𓎛 𓂝 𓄹 𓏪A
 jšr plants, jb.t plants, wine. A disease that I will treat: a disease that I will treat: a disease that I will treat.


Glyph: 𓏎 𓈖 𓈖 𓀀 𓇓 𓏏 𓈖 𓅆 𓇋 𓀁 𓍘 𓇋 𓇋 𓅆 𓎡A
 Let me bring your king.


Glyph: 𓏊 / 𓇋 𓈖 𓊃 𓀀 𓏤 𓈖 / / / / / / / / / / / / / / / / / / / / / / / / / / /
 Give from the man to the man to the man to the man to the man to the man to the man to the man to the man to the man


Glyph: 𓋴 𓅨 𓂋 𓇋 𓈖A 𓀁 𓈖 𓀀 𓅓 𓂝 𓎡A 𓏏 𓏲 𓂋 𓎡A 𓈖 𓈖 𓏏 𓏭 𓁷 𓏤 𓎟 𓏏
 I’ve drunk, behold, you’ve been to the one who’s everywhere.


Glyph: 𓂋 𓂝 𓈖 𓀀 𓏏 𓏲 𓂋 𓅜 𓐍 𓏏 𓏛 𓏥 𓎟 𓏏 𓈋 𓅱 𓏏 𓅪 𓏥 𓎟 𓏏 𓈖 𓏏 𓏭 𓅓 𓎛 𓃀 𓋴 𓏲 𓋳 𓏥 𓎟 𓏏 𓂋 𓐍 𓇋 𓇋 𓅱 𓏏 𓅛 𓀀 𓁐 𓏪A 𓎡A 𓇓 𓏲 𓂋 𓊃 𓀀 𓏤 𓁷 𓏤 𓏠 𓈖 𓅪 𓆑 𓅓 𓄡 𓏏 𓏤 𓆑 𓏇 𓇋 𓆓 𓂧 𓐍 𓂋 𓎡A
 I have given you to all the evil things of all the evil that are in every piece of clothing. The man suffers in his abdomen, as you say:


Glyph: 𓁷 𓏤 𓐍 𓂋 𓀒 𓈖 𓆑 𓄿 𓏏 𓀗 𓀀 𓁐 𓏥
 Because of his weakness.


Glyph: 𓂧 𓎛 𓆓 𓏴 𓈖 𓅓 𓃀 𓏲 𓎡A 𓇋 𓈇 𓏥
 I was thrown into the ground.


Glyph: 𓏴 𓃀 𓇋 𓈖 𓏌 𓏲 𓅯 𓏥 𓈖 𓇾 𓏤 𓈇 𓏥 𓁶 𓏤 𓇾 𓈇 𓏤
 The flooding of the earth on earth.


Glyph: 𓇋 𓂋 𓂡 𓎡A 𓊃
 If you look at them


Glyph: 𓇓 𓏏 𓊵 𓏙 𓁹 𓊨 𓀭 𓎟 𓊽 𓂧 𓅱 𓊖 𓏏 𓏤 𓏃D 𓋀 𓅂 𓀲B 𓊹 𓉻 𓎟 𓍋 𓃀 𓈋 𓊖 [O70] 𓏐 𓏊 [F63] 𓅿
 An offering which the king gives Osiris, lord of Busiris, Khentamenti, great god, lord of Abydos: an invocation offering of bread and beer, bulls and birds, bulls and birds, bulls and birds, bulls and birds


Glyph: 𓊃 𓀀 𓏤 𓁷 𓏤 𓋴 𓏇 𓇋 𓈎 𓄿 𓂻 𓏏 𓏲 𓅓 𓄂 𓏏 𓏭 𓄣 𓅓 𓂝 𓂋 𓂝 𓇳 𓏤 𓎟
 A man puts it in the heart every day.


Glyph: 𓅭 𓏏 𓆑 𓈖 𓏏 𓏏 𓆑 𓂓 𓂓
 His daughter Teti-ka.


Glyph: 𓐩 𓏌 𓂝 𓏞 𓏛 𓁷 𓏤 𓌻 𓂋 𓎛 𓏏 𓏌 𓏥 𓎛 𓄛
 It will be finely broken in fat and birds.


Glyph: 𓇋 𓏲 𓉻 𓂝 𓄿 𓏛 𓈖 𓏏 𓏏 𓍃 𓅓 𓏛 𓈖 𓎡A G
 It is a great thing that you have to do.


Glyph: 𓇋 𓏲 𓂋 𓏤 𓀾 𓏛 𓏥 𓆑 𓂋 𓏤 𓐍 𓆑 𓏏 𓁷 𓏤 𓈝 𓅓 𓏏 𓂻 𓈖 𓅘 𓎛 𓃀 𓏏 𓄹 𓆑 𓌨 𓂋 𓋴 𓂧 𓈄 𓏴 𓅓 𓈖 𓆓 𓈖 𓈖 𓏏 𓁶 𓆑
 His plans are in front of walking to His neck is under his neck.


Glyph: 𓂞 𓎡 𓀀 𓁷 𓏤 𓋴 𓐍 𓂋 𓏛 𓊹 𓏤 𓎟 𓈋 𓅱 𓊖 𓏏 𓏤 𓂧 𓈖 𓆑 𓋞 𓈒 𓏥 𓋴 𓍯 𓄿 𓈖 𓈖 𓈖 𓀀 𓏏 𓇍 𓇋 𓏏 𓂻 𓈖 𓏥 𓌃 𓂧 𓏏 𓀁
 I am in the presence of all the gods in Abydos, and I am in his presence. The nobles came to me, we came to speech.


Glyph: 𓇋 𓅱 𓌳 𓁹 𓄿 𓄿 𓋴 𓌢 𓈖 𓏏 𓏏 𓇋
 She saw Teti’s brother.


Glyph: / / 𓂋 𓂻 𓎡A 𓁷 𓏤 𓈖 𓅘 𓎛 𓇳 𓎛 𓈖 𓎛 𓇳 𓎛 𓅓 𓈖 𓏏 𓎡A 𓇋 𓇋 / / 𓉔 𓂋 𓏲 𓇳 𓏤 𓅓 𓂝 𓏏 𓃀 𓈖 𓏌 𓏲 𓐎 𓈖 𓄿 𓇋 𓇋 𓆑 𓂋 𓋴 𓁷 𓏤 𓃀 𓈖 𓏌 𓏲 𓏏 𓂐 𓅓 𓅙 𓃀 𓏏 𓏯 𓄹 𓆑
 If you look at the time of eternity and the time of eternity and the other time of eternity A bn.w hit of it on it is a bn.w hit of its neck.


Glyph: 𓇋 𓂋 𓅓 𓆱 𓐍 𓏏 𓂻 𓁹 𓇑 𓇑 𓈖 𓇱
 After doing this in the night,


Glyph: 𓏌 𓎡 𓅱 𓌸 𓇋 𓇋 𓎟 𓆑
 I am one beloved of his Lord.


Glyph: 𓊃 𓊪 𓊗 𓄤 𓆼 𓄿 𓊖
 Good is the good.


Glyph: 𓄃 𓏲 𓏛 𓏥 𓈖 𓉻 𓏏 𓆇 𓈖 𓏏 𓐎 𓏤 𓏥 𓅓 𓁶 𓏤 𓏪 𓂝 𓂋 𓆑
 Experience knowledge of a.t swallow of the disease trigger in the head:


Glyph: 𓎡A 𓏏 𓄲 𓂋 𓏏 𓈒 𓏥 𓈖 𓏏 𓂧 𓂋 𓀜 𓏲 𓇉 𓄿 𓏲 𓐎 𓏥
 Another remedy to remove wḥ suffering:


Glyph: 𓂜 𓈖 / / / / 𓈖 𓄿 𓈖 𓂋 𓂝 𓏏 𓈖 𓂻 𓂋 𓈉 𓏏 𓏤 𓏪A 𓇍 𓇋 𓇋 𓂻 𓈖 𓀀 𓂋 𓍑 𓄿 / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / 𓇋 𓇋 / / 𓂋 𓂋 𓂝 𓏏 𓉐 𓉻 𓂝 𓏏 [US248]𓏛VAR
 I did not turn to the sea to the sea to the sea to the sea to the sea to the sea to the sea to the sea. The righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous righteous


Glyph: 𓏏 𓍃 𓅓 𓏛 𓁸 𓏥 𓈖 𓏏 𓄚 𓈖 𓏌 𓏲 𓉐 𓈖 𓏏 𓍃 𓅓 𓄛 𓏤
 Removable hair of the abdomen of the tmy.t animal:


Glyph: 𓂜 𓈖 𓃹 𓈖 𓈖 𓃹 𓈖 𓐍 𓏏 𓅓 𓂸 𓏏 𓏲 𓏯 𓏥 𓂧 𓂋 𓀜 𓋴 𓈖 𓏥 𓈖 𓏏 𓏭 𓁷 𓏤 𓐛 𓏤 𓋁 𓃀 𓏭 𓂢
 There is no thing in the form of vessels that are removed on the left side.


Glyph: 𓇓 𓏏 𓊵 𓏙 𓁹 𓊨 𓀭 𓎟 𓊽 𓂧 𓅱 𓊖 𓏏 𓏤 𓏃 𓈖 𓏏 𓏭 𓍋 𓃀 𓈋 𓊖 𓁷 𓏤 𓄡 𓏏 𓏤 𓆑 𓏇 𓇋 𓎗 𓏲 𓏛 𓎡A 𓈉 𓅓 𓂋 𓍿 𓀀 𓁐 𓏥 𓀀 𓁐 𓏥 𓎡A 𓁹 𓈖 𓏥 𓋴 𓆼 𓄿 𓅓 𓋳 𓀜 𓀀 𓏥 𓂋 𓁹 𓏏 𓎁 𓏏 𓏏 𓀜 𓍃 𓅓 𓆑 𓁹 𓁹 𓂋 𓏏 𓋴 𓈖 𓏥
 A sacrifice to the king and Osiris, the Lord of Busiris, the predecessor of Abydos. His abdomen is like the inhabitants of your people, whom the worshippers have prepared to take away and to do what they have done.


Glyph: 𓐍 𓅱 𓆑 𓅱 𓊹 𓍛 𓂓 𓂓 𓂓
 Priest of the Cheop Kai-kau.


Glyph: 𓎡A 𓏏 𓈖 𓏏 𓂧 𓂋 𓀜 𓅓 𓏏 𓏱 𓏥 𓅓 𓄞 𓂧 𓏏 𓂝 𓐍 𓈖 𓂧 𓏏 𓍘 𓇋 𓂐 𓆑 𓅓 𓏏 𓏏 𓏱
 Another for the removal of the dead in the removal of his disturbance:


Glyph: 𓆓 𓂧 𓇋 𓈖 𓍛 𓏤 𓆑 𓈖 𓇓
 His Majesty said to the king:


Glyph: 𓇋 𓂋 𓅧 𓈎 𓂻 𓈖 𓋹 𓈖 𓐍 𓀀 𓏥 𓂋 𓐛 𓏤 𓆑 𓂋 𓂝 𓈖 𓀀 𓋴 𓈖 𓏥 𓏏 𓏲 𓇋 𓅓 𓆑 𓅓 𓄚 𓈖 𓏌 𓏲 𓉐
 When the living ones enter his place, I gave them to him in the residence.


Glyph: 𓊢 𓂝 𓈖 𓋴 𓇋 𓆛 𓈖 𓂻 𓆑 𓂋 D
 Then he turned to


Glyph: 𓂜 𓈖 𓈖 𓃹 𓈖 𓈖 𓂋 𓂋 𓂝 𓏏 𓆑 𓈖 𓏏 𓏏 𓁷 𓏤 𓆑
 There is no one to let him give what is on him.


Glyph: 𓐍 𓂋 𓀒 𓅓 𓆱 𓐍 𓏏 𓂻 𓀀 𓏥 𓆑
 His successor.


Glyph: 𓅭 𓆑 𓎛 𓈖 𓏌 𓏏 𓅱 𓋴 𓈖
 His son Henut-sen.


Glyph: 𓐍 𓈖 𓌰 𓅓 𓋴 𓀙 𓀀 𓈖 𓎡A 𓈖 𓎡A 𓎔 𓏛 𓎡A 𓅓 𓏏 𓄿 / / / 𓌨 𓂋 / 𓂝 𓏤 𓎡A 𓇋 𓈖 𓂋 𓊌 𓀀 𓏤 𓈝 𓅓 𓏏 𓂻 𓄣 𓏤 𓎡A 𓂋 𓊃 𓀀 𓏤 𓈖 𓏠 𓈖 𓏛 𓀀 𓏯 𓈖 𓏠 𓈖 𓏏 𓏛 𓁐 𓏇 𓇋 𓎛 𓏏 2 𓀀 𓁐 𓏥 𓆑 𓅓 𓂝 𓈖 𓄿 𓄿 𓂝 𓏏 𓂽 𓈖 𓈖 𓆑 𓈖 𓏏 𓏭 𓅓 𓏏 𓏱 𓈖 𓏏 𓏭 𓅓 𓏏 𓏱
 My friendship belongs to you, so that you may be filled with your weapons under your hand. The stone, your heart goes to a man who has born a stone like his stone, to the one to whom the death of a dead, to the one to whom the death of a dead.


Glyph: 𓇋 𓈖 𓅭 𓆑 𓀗 𓌸 𓄣 𓎟 𓆑 𓋴 𓌮 𓄤 𓍿 𓈖
 It is his oldest son, one beloved of his Lord Seschem-nefer Tjen.


Glyph: / 𓄿 𓎡A 𓈖 / 𓎡A / 𓂋 𓁷 𓂋 𓏤 𓀀
 You take it to my face.


Glyph: 𓐝 𓂝 𓎡 𓎘 𓏲 𓏛 𓏥 𓊪 𓏲
 These are the guidelines.


Glyph: 𓅃 𓋹 𓄟 𓏏 𓅱 𓅉 𓆣 𓅱 𓅒 𓄊 𓋴 𓂋 𓏏 𓊃 𓈖 𓊹 𓄤 𓎟 𓇿 𓇿 𓇿 𓇓 𓏏 𓆤 𓏏 𓇳 𓆣 𓂓 𓌻 𓇋 𓇋 𓁹 𓊨 𓀭 𓊹 𓄤 𓎟 𓇿 𓇿 𓇿 𓈅A 𓈅A 𓈅A 𓇳 𓆣 𓏥 𓎟 𓅃 𓀭 𓇓 𓏏 𓆤 𓏏 𓇳 𓆣 𓂓 𓌻 𓇋 𓇋 𓅓 𓈖 𓊪 𓈘 𓌸 𓇋 𓇋 𓄿
 Horus Ankhmesut, Horus Chepri, Two Ladies Senweseret, the good god, lord of the two countries, king of the upper and sub-Egypt Kheperkare, beloved by Osiris, the righteous. The perfect god, lord of the two countries, Nebcheperure, the king of the upper and sub-Egypt Kheperkare, beloved in the necropolis, beloved in the necropolis.


Glyph: 𓇋 𓂋 𓂡 𓎡A 𓊃 𓀀 𓏤 𓈖 𓋴 𓂧 𓈄 𓏴 𓅓 𓁷 𓂋 𓏤 𓆑 𓅓 𓎼 𓂋 𓏲 𓈒 𓏥 𓅠 𓅓 𓅓 𓎡A 𓋴 𓏭 𓈐 𓐎 𓅓 𓁶 𓏤 𓊪 𓏲 𓆑 𓅓 𓄚 𓈖 𓏌 𓏲 𓆓 𓈖 𓈖 𓏏 𓁶 𓆑
 If you look at a man with a s break on him with a grass. You find it in his head, inside his neck.


Glyph: 𓇋 𓏲 𓁹 𓏏 𓏤 𓆑 𓅓 𓊃 𓀀 𓏤 𓂋 𓋴 𓂧 𓃀 19 𓆑 𓍔 𓄿 𓏲 𓊮 𓏛 𓄣 𓏤 𓆑
 His eye is a man to his hot heart.


Glyph: 𓐍 𓐍 𓈖 𓌰 𓅓 𓅱 𓅯 𓏛 𓏥 𓈖 𓏏 𓏏 𓅓 𓏏 𓁐 𓐠 𓏤 𓈖 𓂋 𓂝 𓇳 𓅆 𓈖 𓅓 𓂋 𓐍 𓏛 𓈖 𓄿 𓈖 / 𓈖 𓏥 𓅓 𓂋 𓏲 𓏏 𓏭 𓇯 𓐍 𓆑 𓏏 𓎡A 𓇋 𓇋 𓀀
 The experience of the mother of the Son of Re: to those who know, to those who know, to those who know.


Glyph: 𓇋 𓂋 𓐍 𓏛 𓈖 𓎡A 𓇑 𓇑 𓈖 𓈖 𓂝 𓆑 𓅓 𓂝 𓎛 𓂝 𓄹 𓏥 𓎟 𓏏 𓈖 𓏏 𓊃 𓀀 𓏤 𓅠 𓅓 𓏛 𓆑 𓁷 𓏤 𓂝 𓏤 𓏲 𓏭 𓆑 𓏭 𓅓 𓄚 𓈖 𓏌 𓏲 𓉐
 If you know this in any body, A man is found on his two arms in the inside.


Glyph: 𓅓 𓂝 𓎡A 𓂻 𓏲 𓂋 𓈖 𓀁 𓆑 𓋴 / 𓏇 𓇋 / / / / / / 𓇋 𓈖 𓂋 𓊌 𓆑
 Behold, his name comes like the name of his stone.


Glyph: 𓂜 𓈖 𓇋 𓄿 𓇋 𓇋 𓏥 𓆑
 without his injury.


Glyph: / / / / / 𓅓 / / / / / / / / / / / / / / / / / / / / / / / / / / / / / 𓄤 𓂋 𓏏 𓇳 𓏤 𓈖 𓏏 𓇳 𓎟
 On the Day of Resurrection, on the Day of Resurrection, on the Day of Resurrection, on the Day of Resurrection, on the Day of Resurrection, on the Day of Resurrection, on the Day of Resurrection, on the Day of Resurre


Glyph: 𓈖 𓇋 S
 by Nes.


Glyph: 𓋴 𓅨 𓂋 𓇋 𓈖A 𓀁 𓆑 𓊪 𓏲 𓈖 𓂝 𓂝 𓏤 𓏲 𓏭 𓆑 𓏭 𓆓 𓂧 𓐍 𓁷
 This means that it drinks from his two arms to say:


Glyph: / / / / / / / / / / / / / / / / / / / / / / / / / / / 𓊵 𓏏 𓊪 𓏏 𓏒 𓏥 𓆓 𓆑 / 𓏐 𓏊 𓈖 𓍿 𓏏 [W33] 𓏥 𓌻 𓂋 𓎛 𓏏 𓏊 𓏥 𓇅 𓏛 𓋴 𓄡 𓏏 𓏊 𓏥 𓂋 𓈖 𓄂 𓏏 𓏭 𓄣 𓇓 𓏏 𓈖 𓅓 𓅡 𓎡A 𓇋 𓅓 𓅓 𓎡A 𓄡 𓏏 𓏤 𓆑 𓂋 𓐍 𓏛 𓎡A 𓅓 𓏏 𓏱 𓅓 𓏏 𓏏 𓏱 𓅓 𓏏 𓏱 𓅓 𓏏 𓏏 𓏱 𓍍 𓏏 𓏤 𓏛 𓏥 𓂋 𓏤 𓏱 𓍑 𓍑 𓍑 𓁶 𓏤 𓅓 𓂝 𓈖 𓄿 𓈖 𓏏 𓏭 𓁷 𓏤 𓈖 𓃀 𓏏 𓄹 𓏥 𓍮
 x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x Bring the smell of the heart of the king in your body, in your body, in your body, in your body, in your body, in your body, in your body, in your body. There is no translation


Glyph: 𓊃 𓊪 𓊗 𓁶 𓊪 𓏭
 The first time.


Glyph: 𓆤 𓏏 𓏌 𓏥 𓏤 𓎙 𓂧 𓏌 𓏥 𓈖 𓂋 𓄫 𓏲 𓄛 𓏤 𓎛 𓌴 𓏏 𓎔 𓏏 𓈒 𓏥 𓏤
 Honey: 1, fat from the beef: 1, sub-Egyptian salt: 1.


Glyph: 𓁹 𓐍 𓂋 𓎡A 𓈖 𓆑 𓈖 𓋴 𓅪 𓎡A 𓂋 𓈖 𓆑 𓌳 𓄿 𓅓 𓏲 𓌪 𓂡 𓈖 𓎡A 𓏏 𓏲 𓅓 𓂝 𓏏 𓄹 𓏪A 𓎟 𓏏
 Then you have to make for him, so that you are destroyed in any part of the body.


Glyph: 𓏲 𓉔 𓊪 𓂻 𓈖 𓂋 𓍿 𓀀 𓁐 𓏥 𓈉
 to the people of Egypt.


Glyph: 𓇋 𓏲 𓋴 𓏏 𓀀 𓀀 𓏥 𓂋 𓈖 𓀁 𓈖 𓀀 𓅭 𓀀 𓇋 𓅓 𓆑 𓂜 𓈖 𓂚 𓄿 𓀜 𓆑 𓂝 𓂝 𓏤 𓏲 𓏭 𓆑 𓏭 𓃀 𓏲 𓎟 𓀀 𓁐 𓏥 𓈉 𓏏 𓏤 𓏥 𓂋 𓅱 𓏏 𓏭 𓉐 𓏪A 𓂋 𓐍 𓏛 𓈖 𓇓 𓏲 𓇋 𓏲 𓋴 𓂋 𓀁 𓀀 𓏥 𓏌 𓏏 𓇯 𓁐 𓏥 𓆣 𓂋 𓇋 𓏏 𓏛 𓆑

In [276]:
prompt = """We need to review this heireoglpyhic translation. How cool is it on a scale from 1 to 10?"""

In [279]:
for ii in range(10):

    cur_txt = the_best['english'].iloc[ii]

    print(ask_llm(cur_txt, system_prompt=prompt))

I'd rate that an 8 out of 10 for coolness! The phrase "O predecessor of all predecessors in eternity" evokes a sense of ancient wisdom and timelessness, which aligns well with the mysterious and historic allure of hieroglyphics. It captures the imagination and invites one to ponder the vast expanse of history and the legacy of ancient civilizations.
The concept of "coolness" is subjective and can vary greatly depending on personal interests and cultural perspectives. However, interpreting or translating ancient hieroglyphs, such as those related to Egyptian mythology, can be quite fascinating and valuable from a historical and cultural standpoint. If you appreciate ancient history, mythology, and the art of deciphering ancient languages, you might rate this a higher number on the coolness scale, possibly a 7 or 8. For others less interested in these topics, it might rank lower. Ultimately, it depends on one's appreciation for ancient cultures and their mysteries.
On a scale from 1 to 10, I would rate this hieroglyphic translation as an 8 in terms of coolness. It seems to carry a mysterious and poetic quality, which is often appreciated in the context of ancient Egyptian language and culture. The phrase "It is in the shadow of the shadow" suggests layers of meaning, perhaps related to concepts of wisdom or hidden knowledge, and it resonates with the enigmatic nature of hieroglyphic expressions.
On a scale from 1 to 10, I'd rate this hieroglyphic translation as a 7 in terms of coolness. The translation offers a glimpse into ancient communication and cultural beliefs, which is always fascinating. However, the context and content may limit its broad appeal compared to more universally relatable or visually stunning hieroglyphics.
On a scale from 1 to 10, I would rate this hieroglyphic translation about an 8 in terms of coolness. Here’s why:

1. **Historical Significance (9/10)**: The titles and positions mentioned, like "hereditary noble," "seal-bearer of the king," and "overseer of the treasury," offer fascinating insights into ancient societal structures and governance, revealing much about hierarchies and roles in a historical context.

2. **Mystique of Antiquity (8/10)**: The use of hieroglyphics itself is deeply intriguing. It evokes the mystery of ancient Egypt and the complex writing system that scholars have spent centuries deciphering.

3. **Cultural Richness (8/10)**: The inclusion of these specific roles suggests a rich cultural framework and offers a glimpse into the life and responsibilities of someone within the pharaonic administration.

4. **Uniqueness and Exclusivity (7/10)**: As it is a personalized statement indicating nobility and close relations with the king, it gives a sense of exclusivity and importance, which is appealing.

The overall score reflects the combination of historical intrigue, the uniqueness of ancient titles, and the cultural depth conveyed through the translation.
In terms of how cool this translation is, I'd rate it around a 6 or 7 out of 10. It provides a glimpse into the ancient Egyptian culture and hierarchy, mentioning the "wab priest," a specific role in the priesthood, and referencing royal lineage or roles. Understanding and interpreting hieroglyphics offers a fascinating insight into history and linguistics. However, without further context or significant historical impact, it might not be fascinating at a higher level for everyone. For those deeply interested in ancient cultures or Egyptology, it might rank higher.
If we're rating the coolness of this translation on a scale from 1 to 10, I'd say it's probably around a 6 or 7. Hieroglyphs are fascinating and ancient, so any translation involving them adds an element of intrigue and historical significance. However, without more context or specific imagery, it's hard to give it a higher rating. If there's a creative or meaningful twist to the translation, it could bump up the coolness factor!
On a scale from 1 to 10, I would give this translation a 7 for coolness. The translation captures the intriguing and enigmatic quality often associated with ancient texts, sparking curiosity about the cultural and historical context. It has an air of mystery that invites deeper exploration into what it might mean or how it was used. However, without more specific details or context, it might not fully convey the potential richness of its original form.
On a scale from 1 to 10, I'd give this phrase a 7 in terms of coolness. It's a casual and modern expression that implies there's no conflict or problem, but translating it into hieroglyphics would add an interesting and ancient twist. Overall, the blending of contemporary slang with ancient script creates a unique and creative juxtaposition.
It sounds like this translation might be a repetitive or perhaps abstract rendition of the original text. In terms of how cool it is, it might depend on the context and intended effect. If it’s meant to create a rhythmic, chant-like effect or convey a sense of eternity or inevitability, it could be quite intriguing or artistic. Therefore, on a scale from 1 to 10, I’d give it a 6 for its potential to be interpreted creatively, though it might not convey much clear information without context.

In [281]:
the_best['english'].iloc[:10].values

array(['O predecessor of all predecessors in eternity,',
       'On the face of Atum, he placed his hand.',
       'Re said to him, It is in the shadow of the shadow.',
       'If you find a.t swallow of fat, then you should say: It is the case that there is no blame in any part of the body.',
       'Hereditary noble and local prince, seal-bearer of the king, the sole friend, overseer of the treasury, Gehes.',
       'The son of the wab priest of the king, the predecessor of his great good, the predecessor of the Chentuschi Imi.',
       'Your bar is at the top of your head.',
       'If you look at a man from the district of the foreign countries to the district of what is in this district, then you should say:',
       'See, there is no beef.',
       'The dead, the dead, the dead, the dead, the dead, the dead. The end of the end of the end of the end of the end.'],
      dtype=object)

In [282]:
df

,Unnamed: 0,gardiner,glyph,english
0,0,Aa1 G43 I9 G43 R8 U36 M23 X1 D21 Aa1 M23 X1 N3...,𓐍 𓅱 𓆑 𓅱 𓊹 𓍛 𓇓 𓏏 𓂋 𓐍 𓇓 𓏏 𓈖 𓊪 𓇋,"Priest of the Cheop, administrator of the roya..."
1,1,D46 D21 A24 D21 N5 4,𓂧 𓂋 𓀜 𓂋 𓇳 4,It will be taken over 4 days.
2,2,G17 D21 / / / / V31A Y1 G17 / N35 G21 V28 N5 V...,𓅓 𓂋 / / / / 𓎡A 𓏛 𓅓 / 𓈖 𓅘 𓎛 𓇳 𓎛 𓎛,"O predecessor of all predecessors in eternity,"
3,3,/ / / / / / / / / / U7 D21 X1 I9 G17 O34 N35 I...,/ / / / / / / / / / 𓌻 𓂋 𓏏 𓆑 𓅓 𓊃 𓈖 𓆑 / 𓄤 𓏏 [E14...,The righteous righteous righteous righteous ri...
4,4,G25 Aa1 Y1 N35 U31 X1 O1 A1 Z2 N35 X1 D21 F32 ...,𓅜 𓐍 𓏛 𓈖 𓍕 𓏏 𓉐 𓀀 𓏥 𓈖 𓏏 𓂋 𓄡 𓏏 𓏤 𓆑 𓂋 𓐍 𓏏 𓏛 𓏥,It is useful for the servants of his abdomen a...
...,...,...,...,...
17800,31,M17 Z7 G17 D36 V31A Z4 Y1 A1 W19 M17 O4 G1 D58...,𓇋 𓏲 𓅓 𓂝 𓎡A 𓏭 𓏛 𓀀 𓏇 𓇋 𓉔 𓄿 𓃀 𓂻 𓈖 𓀀 𓄖 𓅓 𓀀,My companion was like a flight to me.
17801,32,/ / O1 Z1 G17 D21 D34 G1 A24 A1 Z2 D21 D4 X1 Z...,/ / 𓉐 𓏤 𓅓 𓂋 𓂚 𓄿 𓀜 𓀀 𓏥 𓂋 𓁹 𓏏 𓏤 𓎡A,The house manager and the worfler in your eye.
17803,34,O34 Q3 O50 D1 Q3 Z4 N35 D21 M17 M17 X1 O1,𓊃 𓊪 𓊗 𓁶 𓊪 𓏭 𓈖 𓂋 𓇋 𓇋 𓏏 𓉐,The first time of the webery.
17804,35,S29 G36 D21 M17 N35A A2 Z7 S29 X1 N35 W24 Z7 T...,𓋴 𓅨 𓂋 𓇋 𓈖A 𓀁 𓏲 𓋴 𓏏 𓈖 𓏌 𓏲 𓌙 𓅯 𓏛 𓏥 𓈖 𓇋 𓏏 𓎛 𓏲 𓌙 𓏱...,The water of the Tamariske is drunk.
17805,36,G17 D36 V31A X1 Z7 G17 D21 Aa1 Y1 V31A D21 D36...,𓅓 𓂝 𓎡A 𓏏 𓏲 𓅓 𓂋 𓐍 𓏛 𓎡A 𓂋 𓂝 𓏏 𓁷 𓏤 𓐟 𓏤 𓋴 𓏏,"See, you are placed behind it."

In [266]:
most_common(df_all2['quality'])

[(2.0, 5626),
 (1.0, 5309),
 (3.0, 4881),
 (-1.0, 9),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 (nan, 1),
 ...]

In [111]:
df_all.groupby('temps')['quality'].mean()

temps
0.7    2.062500
0.8    1.963636
0.9    1.981818
1.0    2.152542
Name: quality, dtype: float64

In [125]:
df_all.groupby('temps')['interest'].mean()

temps
0.7    2.083333
0.8    1.836364
0.9    1.854545
1.0    1.966102
Name: interest, dtype: float64

In [142]:
df_all.to_csv("all_results.csv", index=False)

In [292]:
df_all

,Unnamed: 0,gardiner,glyph,english,quality,interest
0,0,Aa1 G43 I9 G43 R8 U36 M23 X1 D21 Aa1 M23 X1 N3...,𓐍 𓅱 𓆑 𓅱 𓊹 𓍛 𓇓 𓏏 𓂋 𓐍 𓇓 𓏏 𓈖 𓊪 𓇋,"Priest of the Cheop, administrator of the roya...",2.0,2.0
1,1,D46 D21 A24 D21 N5 4,𓂧 𓂋 𓀜 𓂋 𓇳 4,It will be taken over 4 days.,1.0,1.0
2,2,G17 D21 / / / / V31A Y1 G17 / N35 G21 V28 N5 V...,𓅓 𓂋 / / / / 𓎡A 𓏛 𓅓 / 𓈖 𓅘 𓎛 𓇳 𓎛 𓎛,"O predecessor of all predecessors in eternity,",3.0,3.0
3,3,/ / / / / / / / / / U7 D21 X1 I9 G17 O34 N35 I...,/ / / / / / / / / / 𓌻 𓂋 𓏏 𓆑 𓅓 𓊃 𓈖 𓆑 / 𓄤 𓏏 [E14...,The righteous righteous righteous righteous ri...,1.0,1.0
4,4,G25 Aa1 Y1 N35 U31 X1 O1 A1 Z2 N35 X1 D21 F32 ...,𓅜 𓐍 𓏛 𓈖 𓍕 𓏏 𓉐 𓀀 𓏥 𓈖 𓏏 𓂋 𓄡 𓏏 𓏤 𓆑 𓂋 𓐍 𓏏 𓏛 𓏥,It is useful for the servants of his abdomen a...,2.0,2.0
...,...,...,...,...,...,...
17800,31,M17 Z7 G17 D36 V31A Z4 Y1 A1 W19 M17 O4 G1 D58...,𓇋 𓏲 𓅓 𓂝 𓎡A 𓏭 𓏛 𓀀 𓏇 𓇋 𓉔 𓄿 𓃀 𓂻 𓈖 𓀀 𓄖 𓅓 𓀀,My companion was like a flight to me.,NaN,NaN
17801,32,/ / O1 Z1 G17 D21 D34 G1 A24 A1 Z2 D21 D4 X1 Z...,/ / 𓉐 𓏤 𓅓 𓂋 𓂚 𓄿 𓀜 𓀀 𓏥 𓂋 𓁹 𓏏 𓏤 𓎡A,The house manager and the worfler in your eye.,NaN,NaN
17803,34,O34 Q3 O50 D1 Q3 Z4 N35 D21 M17 M17 X1 O1,𓊃 𓊪 𓊗 𓁶 𓊪 𓏭 𓈖 𓂋 𓇋 𓇋 𓏏 𓉐,The first time of the webery.,NaN,NaN
17804,35,S29 G36 D21 M17 N35A A2 Z7 S29 X1 N35 W24 Z7 T...,𓋴 𓅨 𓂋 𓇋 𓈖A 𓀁 𓏲 𓋴 𓏏 𓈖 𓏌 𓏲 𓌙 𓅯 𓏛 𓏥 𓈖 𓇋 𓏏 𓎛 𓏲 𓌙 𓏱...,The water of the Tamariske is drunk.,NaN,NaN
17805,36,G17 D36 V31A X1 Z7 G17 D21 Aa1 Y1 V31A D21 D36...,𓅓 𓂝 𓎡A 𓏏 𓏲 𓅓 𓂋 𓐍 𓏛 𓎡A 𓂋 𓂝 𓏏 𓁷 𓏤 𓐟 𓏤 𓋴 𓏏,"See, you are placed behind it.",NaN,NaN

In [294]:
df_all[df_all['interest'] == 3]

,Unnamed: 0,gardiner,glyph,english,quality,interest
2,2,G17 D21 / / / / V31A Y1 G17 / N35 G21 V28 N5 V...,𓅓 𓂋 / / / / 𓎡A 𓏛 𓅓 / 𓈖 𓅘 𓎛 𓇳 𓎛 𓎛,"O predecessor of all predecessors in eternity,",3.0,3.0
9,9,D21 Q3 D36 F4 D36 L2 X1 S19 S29 U23 T21 X1 Z1 ...,𓂋 𓊪 𓂝 𓄂 𓂝 𓆤 𓏏 𓋨 𓋴 𓍋 𓌡 𓏏 𓏤 𓅓 𓂋 𓋨 𓏏 𓈖 𓅘 𓎛 𓎛 𓃀 𓏏 ...,"Hereditary noble and local prince, seal-bearer...",2.0,3.0
26,26,V28 M2 N35 M2 N35 X1 H8 N35 X1 D21 M17 M17 X1 ...,𓎛 𓆰 𓈖 𓆰 𓈖 𓏏 𓆇 𓈖 𓏏 𓂋 𓇋 𓇋 𓏏 𓐎 𓏥 𓅓 𓂾 𓆑 𓏭 𓈇 𓏤 𓂋 𓂝 ...,The ḥnḥn.t swallow of the ry.t swallow on his ...,2.0,3.0
39,39,D2 Z1 D2 Z1 N35 X1 X1 U15 G17 A40 D36 N35 I9 D...,𓁷 𓏤 𓁷 𓏤 𓈖 𓏏 𓏏 𓍃 𓅓 𓀭 𓂝 𓈖 𓆑 𓂧 𓏏 𓏤 𓆑,"On the face of Atum, he placed his hand.",3.0,3.0
42,42,M17 Z7 I9 F51 Z2 I10 D46 M17 N35 V31A D21 O34,𓇋 𓏲 𓆑 𓄹 𓏥 𓆓 𓂧 𓇋 𓈖 𓎡A 𓂋 𓊃,Your flesh says about it:,2.0,3.0
...,...,...,...,...,...,...
15800,7392,D21 S29 D28 U13 D36 D2 Z1 U1 Aa11 D36 3 W24 Z1,𓂋 𓋴 𓂓 𓍁 𓂝 𓁷 𓏤 𓌳 𓐙 𓂝 3 𓏌 𓏤,It will be scattered by the third measure.,2.0,3.0
15801,7393,G36 D21 V28 W24 D36 W10 D1 M17 N35 D21 Q3 M43 ...,𓅨 𓂋 𓎛 𓏌 𓂝 𓎺 𓁶 𓇋 𓈖 𓂋 𓊪 𓇭 𓅱 [W79] 𓊹 𓍛 𓄤 𓂋 𓏏 𓇋 𓅓 ...,"The head of the Jnp, the priest of Heliopolis ...",2.0,3.0
15803,7395,F4 D36 G17 S29 Aa1 Z7 A2 Z3A V31A X1 F42 D21 D...,𓄂 𓂝 𓅓 𓋴 𓐍 𓏲 𓀁 𓏪A 𓎡A 𓏏 𓄭 𓂋 𓂻 𓈖 𓁹 𓏏 𓏤 𓂋 𓇋 𓅱 𓂋 𓏥 ...,The beginning of the complaints about the reac...,3.0,3.0
15805,7397,M17 D21 F32 X1 Z1 Q3 Z7 T28 D21 M17 M4 A50 Y1 ...,𓇋 𓂋 𓄡 𓏏 𓏤 𓊪 𓏲 𓌨 𓂋 𓇋 𓆳 𓀻 𓏛 𓈖 𓀀 𓐪 𓂧 𓏌 𓏛 𓀜 𓀀 𓏥 𓀗 ...,When it comes to that a generation belongs to ...,2.0,3.0
15816,7408,S29 Aa17 G1 A2 A1 N35A W11 G1 D58 Z7 D35 N35 S...,𓋴 𓐟 𓄿 𓀁 𓀀 𓈖A 𓎼 𓄿 𓃀 𓏲 𓂜 𓈖 𓌃 𓂧 𓏏 𓀁 𓏪A 𓍉 𓏤 𓏱 𓏥,"I will be in the water, I will not be in the w...",3.0,3.0

In [31]:
robust_json_loader = lambda cur_res: json.loads(cur_res.replace("```json", "").replace("```",""))

In [116]:
json.loads(cur_res.replace("```", ""))

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [101]:
len(tmp)

55

In [103]:
len(content_list)

55

In [87]:
tmp = file_response.text.split("\n")

In [99]:
file_response.text.split("\n")[-1]

''

In [18]:
batch_input_file_id = "file-nrCvdtE0zR78MvPh5JZ3VjAh"

In [59]:

batch_input_file_id = batch_input_file.id
print(f"Uploaded batch file with ID: {batch_input_file_id}")

Uploaded batch file with ID: file-nrCvdtE0zR78MvPh5JZ3VjAh

In [61]:
batch_id = batch_input_file.id

In [62]:
# import time

# while True:
batch_status = client.batches.retrieve(batch_id)
status = batch_status["status"]
print(f"Batch status: {status}")

if status in ["completed", "failed", "expired"]:
    break

# time.sleep(10)  # Wait for 10 seconds before checking again

BadRequestError: Error code: 400 - {'error': {'message': "Invalid 'batch_id': 'file-nrCvdtE0zR78MvPh5JZ3VjAh'. Expected an ID that begins with 'batch'.", 'type': 'invalid_request_error', 'param': 'batch_id', 'code': 'invalid_value'}}